/** Thumbnail counterpart of a species photo.
 *
 *  Full-size photos (900 px) live under assets/species and are fetched on demand;
 *  the 400 px thumbnails under assets/species-sm are the ones precached, so grids
 *  and lists work offline without an 11 MB first install. Generated by
 *  scripts/thumbs.mjs — the two directories always hold the same filenames.
 */
export function thumbOf(file: string): string {
  return file.replace("assets/species/", "assets/species-sm/");
}
