// Self-host Source Serif 4 so the app has no runtime dependency on Google Fonts
// (privacy: no IP leak; offline: titles render without network). Run once:
//   node scripts/fetch-fonts.mjs
import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36";
const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Source+Serif+4:ital,opsz,wght@0,8..60,600;0,8..60,700;1,8..60,400&display=swap";

const outDir = join(root, "public/assets/fonts");
await mkdir(outDir, { recursive: true });

const css = await (await fetch(CSS_URL, { headers: { "User-Agent": UA } })).text();

// Split into @font-face blocks, keep only latin + latin-ext subsets.
const blocks = css.split("@font-face").slice(1);
let out = "/* Source Serif 4 — self-hosted (generated by scripts/fetch-fonts.mjs) */\n";
let n = 0;
for (const b of blocks) {
  const comment = (b.match(/\/\*\s*([a-z-]+)\s*\*\//) || [])[1] || "";
  if (comment && comment !== "latin" && comment !== "latin-ext") continue;
  const url = (b.match(/url\((https:\/\/[^)]+\.woff2)\)/) || [])[1];
  if (!url) continue;
  const weight = (b.match(/font-weight:\s*([^;]+);/) || [])[1]?.trim() || "400";
  const style = (b.match(/font-style:\s*([^;]+);/) || [])[1]?.trim() || "normal";
  const file = `ss4-${style}-${weight.replace(/\s/g, "")}-${comment || n}.woff2`;
  const buf = Buffer.from(await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer());
  await writeFile(join(outDir, file), buf);
  const range = (b.match(/unicode-range:\s*([^;]+);/) || [])[1];
  out +=
    `@font-face{font-family:'Source Serif 4';font-style:${style};font-weight:${weight};` +
    `font-display:swap;src:url('/assets/fonts/${file}') format('woff2');` +
    (range ? `unicode-range:${range.trim()};` : "") +
    `}\n`;
  n++;
  console.log("✓", file);
}
await writeFile(join(root, "src/fonts.css"), out, "utf8");
console.log(`\nWrote src/fonts.css with ${n} faces.`);
