// Self-host Source Serif 4 so the app has no runtime dependency on Google Fonts
// (privacy: no IP leak; offline: titles render without network). Run once:
//   node scripts/fetch-fonts.mjs
import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36";
const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Source+Serif+4:ital,opsz,wght@0,8..60,600;0,8..60,700;1,8..60,400&display=swap";

const outDir = join(root, "public/assets/fonts");
await mkdir(outDir, { recursive: true });

const css = await (await fetch(CSS_URL, { headers: { "User-Agent": UA } })).text();

// Dans la feuille de Google, le commentaire `/* latin */` PRÉCÈDE le bloc
// qu'il nomme. La version d'avant découpait sur "@font-face" puis cherchait un
// commentaire DANS le morceau : elle attrapait donc celui du bloc SUIVANT.
//
// Deux conséquences, l'une cosmétique et l'autre pas :
//  · chaque fichier héritait du nom du mauvais sous-ensemble (d'où un
//    « ss4-normal-700-6.woff2 » qui ne veut rien dire) ;
//  · le filtre gardait le mauvais bloc, si bien que le sous-ensemble « latin »
//    (U+0000-00FF : é, è, à, ç — tout le français courant) n'était téléchargé
//    que pour la DERNIÈRE face de la feuille. L'italique 400 et le demi-gras
//    600 se retrouvaient sans aucune face couvrant le latin de base, et ces
//    textes sortaient en Georgia, la police de repli, à côté d'un « 2ᵉ » rendu
//    en Source Serif.
//
// On apparie donc explicitement le commentaire et le bloc qui le SUIT.
const paires = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g)];
if (!paires.length) {
  throw new Error("Aucun couple commentaire+@font-face : la feuille de Google a changé de forme.");
}
let out = "/* Source Serif 4 — self-hosted (generated by scripts/fetch-fonts.mjs) */\n";
let n = 0;
for (const [, comment, b] of paires) {
  if (comment !== "latin" && comment !== "latin-ext") continue;
  const url = (b.match(/url\((https:\/\/[^)]+\.woff2)\)/) || [])[1];
  if (!url) continue;
  const weight = (b.match(/font-weight:\s*([^;]+);/) || [])[1]?.trim() || "400";
  const style = (b.match(/font-style:\s*([^;]+);/) || [])[1]?.trim() || "normal";
  const file = `ss4-${style}-${weight.replace(/\s/g, "")}-${comment}.woff2`;
  const buf = Buffer.from(await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer());
  await writeFile(join(outDir, file), buf);
  const range = (b.match(/unicode-range:\s*([^;]+);/) || [])[1];
  out +=
    `@font-face{font-family:'Source Serif 4';font-style:${style};font-weight:${weight};` +
    `font-display:swap;src:url('/assets/fonts/${file}') format('woff2');` +
    (range ? `unicode-range:${range.trim()};` : "") +
    `}\n`;
  n++;
  console.log("✓", file);
}
await writeFile(join(root, "src/fonts.css"), out, "utf8");
console.log(`\nWrote src/fonts.css with ${n} faces.`);
