// GENERATED by scripts/crop-knot-steps.mjs — do not edit by hand.
// Une image par geste, dans l'ordre des `steps` de src/data/knots.ts.
// Chaque vignette porte l'auteur, la licence et la page source de sa planche mère :
// l'attribution doit survivre à la découpe.
import type { MediaEntry } from "./media";

export const KNOT_STEPS: Record<string, MediaEntry[]> = {
  "sang": [
    {
      "file": "assets/knots-steps/sang-1.webp",
      "author": "Chris 73",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:BloodKnot_HowTo.jpg"
    },
    {
      "file": "assets/knots-steps/sang-2.webp",
      "author": "Chris 73",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:BloodKnot_HowTo.jpg"
    },
    {
      "file": "assets/knots-steps/sang-3.webp",
      "author": "Chris 73",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:BloodKnot_HowTo.jpg"
    },
    {
      "file": "assets/knots-steps/sang-4.webp",
      "author": "Chris 73",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:BloodKnot_HowTo.jpg"
    }
  ],
  "chaise": [
    {
      "file": "assets/knots-steps/chaise-1.webp",
      "author": "Luis Dantas",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bowline_in_four_steps.png"
    },
    {
      "file": "assets/knots-steps/chaise-2.webp",
      "author": "Luis Dantas",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bowline_in_four_steps.png"
    },
    {
      "file": "assets/knots-steps/chaise-3.webp",
      "author": "Luis Dantas",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bowline_in_four_steps.png"
    },
    {
      "file": "assets/knots-steps/chaise-4.webp",
      "author": "Luis Dantas",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bowline_in_four_steps.png"
    }
  ],
  "albright": [
    {
      "file": "assets/knots-steps/albright-1.webp",
      "author": "LadyofHats (original) · retouché par Dfred",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Albright_knot_diagram_retouched.png"
    },
    {
      "file": "assets/knots-steps/albright-2.webp",
      "author": "LadyofHats (original) · retouché par Dfred",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Albright_knot_diagram_retouched.png"
    },
    {
      "file": "assets/knots-steps/albright-3.webp",
      "author": "LadyofHats (original) · retouché par Dfred",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Albright_knot_diagram_retouched.png"
    },
    {
      "file": "assets/knots-steps/albright-4.webp",
      "author": "LadyofHats (original) · retouché par Dfred",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Albright_knot_diagram_retouched.png"
    }
  ],
  "boucle": [
    {
      "file": "assets/knots-steps/boucle-1.webp",
      "author": "LadyofHats",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Surgeon's_Loop_knot.svg"
    },
    {
      "file": "assets/knots-steps/boucle-2.webp",
      "author": "LadyofHats",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Surgeon's_Loop_knot.svg"
    },
    {
      "file": "assets/knots-steps/boucle-3.webp",
      "author": "LadyofHats",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Surgeon's_Loop_knot.svg"
    }
  ],
  "texan": [
    {
      "file": "assets/knots-steps/texan-1.webp",
      "author": "Zachary635",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Texas_Rig_Diagram.svg"
    },
    {
      "file": "assets/knots-steps/texan-2.webp",
      "author": "Zachary635",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Texas_Rig_Diagram.svg"
    },
    {
      "file": "assets/knots-steps/texan-3.webp",
      "author": "Zachary635",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Texas_Rig_Diagram.svg"
    },
    {
      "file": "assets/knots-steps/texan-4.webp",
      "author": "Zachary635",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Texas_Rig_Diagram.svg"
    }
  ]
};
