// GENERATED by scripts/fetch-images.mjs — do not edit by hand.
// Each entry points to a locally-embedded image plus its licence attribution.
// Only free licences are accepted (CC0 / Public domain / CC BY / CC BY-SA).

export interface MediaEntry {
  file: string; // path under public/, e.g. "assets/species/sandre.webp"
  author: string;
  license: string;
  sourceUrl: string;
  caption?: string; // e.g. "Adulte" / "Juvénile" (shown in the species gallery)
}

// Species carry an ARRAY of photos (adult, juvenile…) for a gallery.
export const SPECIES_MEDIA: Record<string, MediaEntry[]> = {
  "sandre": [
    {
      "file": "assets/species/sandre.webp",
      "author": "Emőke Dénes",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hal_-_Sander_lucioperca_-_1.jpg"
    },
    {
      "file": "assets/species/sandre-2.webp",
      "author": "Pohled 111",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sander_lucioperca_(Czech_Republic)_06.jpg"
    },
    {
      "file": "assets/species/sandre-3.webp",
      "author": "Lorenz Seebauer",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Juvenile_Zander.jpg",
      "caption": "Juvénile"
    }
  ],
  "brochet": [
    {
      "file": "assets/species/brochet.webp",
      "author": "Arnstein Rønning",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Esox_lucius_(no).JPG"
    },
    {
      "file": "assets/species/brochet-2.webp",
      "author": "Karelj",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Esox_lucius_Prague_Vltava_2.jpg"
    },
    {
      "file": "assets/species/brochet-3.webp",
      "author": "Nervurax Fishing",
      "license": "CC0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Esox_lucius_juvenile.png",
      "caption": "Juvénile"
    }
  ],
  "perche": [
    {
      "file": "assets/species/perche.webp",
      "author": "Christa Rohrbach",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Egli_(Perca_fluviatilis)_001_(cropped).jpg"
    },
    {
      "file": "assets/species/perche-2.webp",
      "author": "B. Schoenmakers",
      "license": "CC BY 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Perca_fluviatilis_(Percidae)_-_(juvenile),_Elst_(Gld),_the_Netherlands.jpg",
      "caption": "Juvénile"
    }
  ],
  "black-bass": [
    {
      "file": "assets/species/black-bass.webp",
      "author": "USFWS Mountain-Prairie",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Largemouth_Bass_(Micropterus_salmoides)_(51327213074).jpg"
    },
    {
      "file": "assets/species/black-bass-2.webp",
      "author": "USFWS Mountain-Prairie",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Largemouth_Bass_(Micropterus_salmoides)_(53118787625).jpg"
    },
    {
      "file": "assets/species/black-bass-3.webp",
      "author": "Sam Stukel (USFWS)",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Largemouth_Bass_Fingerling_(9515420177).jpg",
      "caption": "Juvénile"
    }
  ],
  "silure": [
    {
      "file": "assets/species/silure.webp",
      "author": "Bernard Dupont",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:European_Catfish_(Silurus_glanis)_(13532617795).jpg"
    },
    {
      "file": "assets/species/silure-2.webp",
      "author": "Dieter Florian",
      "license": "CC BY-SA 3.0 de",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Silurus_glanis_02.jpg"
    }
  ],
  "gremille": [
    {
      "file": "assets/species/gremille.webp",
      "author": "Gilles San Martin",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gymnocephalus_cernua.jpg"
    }
  ],
  "carpe": [
    {
      "file": "assets/species/carpe.webp",
      "author": "Reaperman",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Carp_(Cyprinus_carpio)_in_aquarium.JPG"
    },
    {
      "file": "assets/species/carpe-2.webp",
      "author": "Sardaka",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:(1)Carp_Centennial_Park.jpg"
    },
    {
      "file": "assets/species/carpe-3.webp",
      "author": "Sam Stukel (USFWS)",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Common_Carp_(Cyprinus_carpio)-8_(51221817512).jpg",
      "caption": "Juvénile"
    }
  ],
  "gardon": [
    {
      "file": "assets/species/gardon.webp",
      "author": "Peter van der Sluijs",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Blankvoorn_gevangen_met_een_hengel_kan_wel_50cm_lang_worden.jpg"
    },
    {
      "file": "assets/species/gardon-2.webp",
      "author": "B. Schoenmakers",
      "license": "CC BY 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rutilus_rutilus_(Cyprinidae)_-_(juvenile),_Elst_(Gld),_the_Netherlands.jpg",
      "caption": "Juvénile"
    }
  ],
  "barbeau": [
    {
      "file": "assets/species/barbeau.webp",
      "author": "Linie29",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Barbe_Tiergarten_Schoenbrunn.jpg"
    },
    {
      "file": "assets/species/barbeau-2.webp",
      "author": "gailhampshire",
      "license": "CC BY 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Barbel._Barbus_barbus_(32518550835).jpg"
    },
    {
      "file": "assets/species/barbeau-3.webp",
      "author": "Sven.petersen",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Barbus_Barbus_(juvenile).JPG",
      "caption": "Juvénile"
    }
  ],
  "carassin": [
    {
      "file": "assets/species/carassin.webp",
      "author": "Viridiflavus",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:CarassiusCarassius7.jpg"
    },
    {
      "file": "assets/species/carassin-2.webp",
      "author": "Viridiflavus",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:CarassiusCarassius8.JPG"
    }
  ],
  "rotengle": [
    {
      "file": "assets/species/rotengle.webp",
      "author": "Peter van der Sluijs",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:De_ruisvoorn_goede_sportvis.jpg"
    },
    {
      "file": "assets/species/rotengle-2.webp",
      "author": "Emőke Dénes",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hal_-_Scardinius_erythrophthalmus_-_1.jpg"
    }
  ],
  "truite-fario": [
    {
      "file": "assets/species/truite-fario.webp",
      "author": "USFWS Mountain-Prairie",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Brown_Trout_(Salmo_trutta)_(53678765394).jpg"
    },
    {
      "file": "assets/species/truite-fario-2.webp",
      "author": "USDAgov",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:95cs2032_(49699975643)_(cropped).jpg"
    },
    {
      "file": "assets/species/truite-fario-3.webp",
      "author": "Sam Stukel (USFWS)",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Brown_Trout_Fingerling_(52979322720).jpg",
      "caption": "Juvénile"
    }
  ],
  "truite-arc-en-ciel": [
    {
      "file": "assets/species/truite-arc-en-ciel.webp",
      "author": "USFWS Mountain-Prairie",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Regenbogenforelle_(Oncorhynchus_mykiss)_Seitenansicht_1.jpg"
    },
    {
      "file": "assets/species/truite-arc-en-ciel-2.webp",
      "author": "Eric Engbretson (USFWS)",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Close_up_of_rainbow_trout_fish_underwater_oncorhynchus_mykiss.jpg"
    }
  ],
  "perche-soleil": [
    {
      "file": "assets/species/perche-soleil.webp",
      "author": "Smithsonian Environmental Research Center",
      "license": "CC BY 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lepomis_gibbosus_(S0167)_(12597958823).jpg"
    },
    {
      "file": "assets/species/perche-soleil-2.webp",
      "author": "Emőke Dénes",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hal_-_Lepomis_gibbosus_-_4.jpg"
    }
  ],
  "poisson-chat": [
    {
      "file": "assets/species/poisson-chat.webp",
      "author": "George Chernilevsky",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ameiurus_melas_2021_G1.jpg"
    },
    {
      "file": "assets/species/poisson-chat-2.webp",
      "author": "Emőke Dénes",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hal_-_Ameiurus_melas_-_4.jpg"
    }
  ],
  "breme": [
    {
      "file": "assets/species/breme.webp",
      "author": "Karelj",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Abramis_brama_Prague_Vltava_1_(cropped).jpg"
    },
    {
      "file": "assets/species/breme-2.webp",
      "author": "Grand-Duc",
      "license": "CC BY-SA 3.0 de",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Abramis_brama_-_2010-09-24_HBP.jpg"
    }
  ],
  "tanche": [
    {
      "file": "assets/species/tanche.webp",
      "author": "Karelj",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tinca_tinca_Prague_Vltava_2.jpg"
    },
    {
      "file": "assets/species/tanche-2.webp",
      "author": "Dezidor",
      "license": "CC BY 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tinca_tinca.jpeg"
    },
    {
      "file": "assets/species/tanche-3.webp",
      "author": "B. Schoenmakers",
      "license": "CC BY 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tinca_tinca_(Cyprinidae)_-_(juvenile),_Elst_(Gld),_the_Netherlands.jpg",
      "caption": "Juvénile"
    }
  ],
  "ablette": [
    {
      "file": "assets/species/ablette.webp",
      "author": "David Perez",
      "license": "CC BY 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alburnus_alburnus_01_by-dpc.jpg"
    },
    {
      "file": "assets/species/ablette-2.webp",
      "author": "Viridiflavus",
      "license": "CC BY 2.5",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alburnus_alburnus_cropped.jpg"
    }
  ],
  "chevesne": [
    {
      "file": "assets/species/chevesne.webp",
      "author": "Emőke Dénes",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hal_-_Squalius_cephalus_-_3.jpg"
    },
    {
      "file": "assets/species/chevesne-2.webp",
      "author": "Tylwyth Eldar",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Oniria_-_Squalius_cephalus_03_(cropped).jpg"
    },
    {
      "file": "assets/species/chevesne-3.webp",
      "author": "Piet Spaans",
      "license": "CC BY-SA 2.5",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:LeuciscusCephalusJuvenile.JPG",
      "caption": "Juvénile"
    }
  ],
  "hotu": [
    {
      "file": "assets/species/hotu.webp",
      "author": "André Karwath (Aka)",
      "license": "CC BY-SA 2.5",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chondrostoma_nasus_(aka)_(cropped).jpg"
    },
    {
      "file": "assets/species/hotu-2.webp",
      "author": "NasserHalaweh",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cyprinidae_Chondrostoma_nasus_1.jpg"
    }
  ],
  "goujon": [
    {
      "file": "assets/species/goujon.webp",
      "author": "Gilles San Martin",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gobio_gobio2.jpg"
    },
    {
      "file": "assets/species/goujon-2.webp",
      "author": "Karelj",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gobio_gobio_Prague_Vltava_2_(cropped).jpg"
    }
  ],
  "ombre": [
    {
      "file": "assets/species/ombre.webp",
      "author": "Gilles San Martin",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Thymallus_thymallus2.jpg"
    },
    {
      "file": "assets/species/ombre-2.webp",
      "author": "Marrabbio2",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Thymallus_thymallus_acqMilano.jpg"
    }
  ],
  "omble-fontaine": [
    {
      "file": "assets/species/omble-fontaine.webp",
      "author": "USFWS",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Brook_trout_01_(cropped).jpg"
    },
    {
      "file": "assets/species/omble-fontaine-2.webp",
      "author": "USDAgov",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:95cs2171_(49700508431).jpg"
    }
  ],
  "anguille": [
    {
      "file": "assets/species/anguille.webp",
      "author": "Vranken Martin",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Anguilla_anguilla_Belgium.jpg"
    },
    {
      "file": "assets/species/anguille-2.webp",
      "author": "jujurenoult",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Anguilla_anguilla_France_(cropped).jpg"
    },
    {
      "file": "assets/species/anguille-3.webp",
      "author": "jujurenoult",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Anguilla_anguilla_glass_eel_France.jpg",
      "caption": "Civelle (juvénile)"
    }
  ],
  "vandoise": [
    {
      "file": "assets/species/vandoise.webp",
      "author": "Viridiflavus",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:LeuciscusLeuciscusSerpeling17.JPG"
    }
  ],
  "breme-bordeliere": [
    {
      "file": "assets/species/breme-bordeliere.webp",
      "author": "Algirdas",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Blicca_bjoerkna.jpg"
    }
  ],
  "spirlin": [
    {
      "file": "assets/species/spirlin.webp",
      "author": "Gilles San Martin",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alburnoides_bipunctatus.jpg"
    }
  ],
  "able-de-heckel": [
    {
      "file": "assets/species/able-de-heckel.webp",
      "author": "Christian Fischer",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:LeucaspiusDelineatus1.jpg"
    }
  ],
  "ide-melanote": [
    {
      "file": "assets/species/ide-melanote.webp",
      "author": "Piet Spaans",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:LeuciscusIdus.JPG"
    }
  ],
  "blageon": [
    {
      "file": "assets/species/blageon.webp",
      "author": "Harka Akos",
      "license": "CC BY 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Telestes_souffia.jpg"
    }
  ],
  "toxostome": [
    {
      "file": "assets/species/toxostome.webp",
      "author": "Julien Renoult",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Parachondrostoma_toxostoma.jpg"
    }
  ],
  "barbeau-meridional": [
    {
      "file": "assets/species/barbeau-meridional.webp",
      "author": "Wikiwiki",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Barbus_meridionalis.jpg"
    }
  ],
  "carassin-argente": [
    {
      "file": "assets/species/carassin-argente.webp",
      "author": "George Chernilevsky",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Carassius_gibelio_2008_G2.jpg"
    }
  ],
  "poisson-rouge": [
    {
      "file": "assets/species/poisson-rouge.webp",
      "author": "George Chernilevsky",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Carassius_wild_golden_fish_2013_G1.jpg"
    }
  ],
  "amour-blanc": [
    {
      "file": "assets/species/amour-blanc.webp",
      "author": "Dezidor",
      "license": "CC BY 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ctenopharyngodon_idella.jpg"
    }
  ],
  "pseudorasbora": [
    {
      "file": "assets/species/pseudorasbora.webp",
      "author": "Piet Spaans",
      "license": "CC BY-SA 2.5",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:PseudorasboraParva2.JPG"
    }
  ],
  "vairon": [
    {
      "file": "assets/species/vairon.webp",
      "author": "Pmau",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Phoxinus_phoxinus_img_33481.jpg"
    }
  ],
  "omble-chevalier": [
    {
      "file": "assets/species/omble-chevalier.webp",
      "author": "Saibling",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Salvelinusalpinus.jpg"
    }
  ],
  "cristivomer": [
    {
      "file": "assets/species/cristivomer.webp",
      "author": "NOAA / GLERL",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lake_Trout_GLERL.jpg"
    }
  ],
  "saumon-atlantique": [
    {
      "file": "assets/species/saumon-atlantique.webp",
      "author": "NOAA / GLERL",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Salmo_salar_GLERL_1.jpg"
    }
  ],
  "coregone-lavaret": [
    {
      "file": "assets/species/coregone-lavaret.webp",
      "author": "Apple2000",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Coregonus_lavaretus_maraena_1.jpg"
    }
  ],
  "huchon": [
    {
      "file": "assets/species/huchon.webp",
      "author": "Harald Peki",
      "license": "Attribution (libre)",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hucho_hucho.jpg"
    }
  ],
  "truite-de-mer": [
    {
      "file": "assets/species/truite-de-mer.webp",
      "author": "Anne Blindheim / Lars Olaf Simonsen",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Salmo_trutta_trutta_retouched.jpg"
    }
  ],
  "brochet-aquitain": [
    {
      "file": "assets/species/brochet-aquitain.webp",
      "author": "MillaTom",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hecht.jpg"
    }
  ],
  "black-bass-petite-bouche": [
    {
      "file": "assets/species/black-bass-petite-bouche.webp",
      "author": "Eric Engbretson (USFWS)",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Micropterus_dolomieu.jpg"
    }
  ],
  "aspe": [
    {
      "file": "assets/species/aspe.webp",
      "author": "Peter van der Sluijs",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Aspius_aspius_snelle_jager_roofblei.jpg"
    },
    {
      "file": "assets/species/aspe-2.webp",
      "author": "Karelj",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Aspius_aspius_Prague_Vltava_3.jpg"
    },
    {
      "file": "assets/species/aspe-3.webp",
      "author": "jujurenoult",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Leuciscus_aspius_juvenile.jpg",
      "caption": "Juvénile"
    }
  ],
  "grande-alose": [
    {
      "file": "assets/species/grande-alose.webp",
      "author": "I. Cheret & L. Metral (Ifremer)",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alose_vraie_(Alosa_alosa)_(Ifremer_00680-79165).jpg"
    }
  ],
  "alose-feinte-atlantique": [
    {
      "file": "assets/species/alose-feinte-atlantique.webp",
      "author": "Hans Hillewaert",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alosa_fallax.jpg"
    }
  ],
  "lamproie-marine": [
    {
      "file": "assets/species/lamproie-marine.webp",
      "author": "Emery Lee (USFWS)",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sea_lamprey_petromyzon_marinus.jpg"
    }
  ],
  "lamproie-de-planer": [
    {
      "file": "assets/species/lamproie-de-planer.webp",
      "author": "Julien Renoult",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lampetra_planeri.jpg"
    }
  ],
  "esturgeon-europeen": [
    {
      "file": "assets/species/esturgeon-europeen.webp",
      "author": "Aah-Yeah",
      "license": "CC BY 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:St%C3%B6r_Sturgeon.jpg"
    }
  ],
  "mulet-porc": [
    {
      "file": "assets/species/mulet-porc.webp",
      "author": "etrusko25",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chelon_ramada_Italy.jpg"
    }
  ],
  "flet": [
    {
      "file": "assets/species/flet.webp",
      "author": "Holger Krisp",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Flunder_Platichthys_flesus.jpg"
    }
  ],
  "epinoche": [
    {
      "file": "assets/species/epinoche.webp",
      "author": "Gilles San Martin",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gasterosteus_aculeatus_-_Epinoche_-_Three-spined_stickleback.jpg"
    }
  ],
  "epinochette": [
    {
      "file": "assets/species/epinochette.webp",
      "author": "Julien Renoult",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pungitius_laevis.jpg"
    }
  ],
  "epinochette-neuf-epines": [
    {
      "file": "assets/species/epinochette-neuf-epines.webp",
      "author": "B. Schoenmakers",
      "license": "CC BY 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pungitius_pungitius_(Gasterosteidae)_-_(length_3_cm),_Elst_(Gld),_the_Netherlands.jpg"
    }
  ],
  "loche-franche": [
    {
      "file": "assets/species/loche-franche.webp",
      "author": "OpenCage",
      "license": "CC BY-SA 2.5",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Barbatula_barbatula_by_OpenCage.jpg"
    }
  ],
  "loche-de-riviere": [
    {
      "file": "assets/species/loche-de-riviere.webp",
      "author": "Ron Offermans",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cobitis_taenia.jpg"
    }
  ],
  "chabot-commun": [
    {
      "file": "assets/species/chabot-commun.webp",
      "author": "mnauky (iNaturalist)",
      "license": "CC BY 4.0",
      "sourceUrl": "https://www.inaturalist.org/observations/91735607"
    }
  ],
  "apron-du-rhone": [
    {
      "file": "assets/species/apron-du-rhone.webp",
      "author": "Julien Renoult (iNaturalist)",
      "license": "CC BY 4.0",
      "sourceUrl": "https://www.inaturalist.org/observations/7718639"
    }
  ],
  "bouviere": [
    {
      "file": "assets/species/bouviere.webp",
      "author": "Viridiflavus",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rhodeus_amarus.jpg"
    }
  ],
  "gambusie": [
    {
      "file": "assets/species/gambusie.webp",
      "author": "etrusko25",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gambusia_holbrooki_1.jpg"
    }
  ],
  "alose-feinte-mediterraneenne": [
    {
      "file": "assets/species/alose-feinte-mediterraneenne.webp",
      "author": "emilvus",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alosa_agone_Garda_lake.jpg"
    }
  ],
  "blennie-fluviatile": [
    {
      "file": "assets/species/blennie-fluviatile.webp",
      "author": "jujurenoult",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Salariopsis_fluviatilis_France.jpg"
    }
  ],
  "carpe-argentee": [
    {
      "file": "assets/species/carpe-argentee.webp",
      "author": "Sam Stukel (USFWS)",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Silver_Carp_Adult_(Hypophthalmichthys_molitrix).jpg"
    }
  ],
  "chabot-fluviatile": [
    {
      "file": "assets/species/chabot-fluviatile.webp",
      "author": "Julien Renoult",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cottus_perifretum.jpg"
    }
  ],
  "chevesne-catalan": [
    {
      "file": "assets/species/chevesne-catalan.webp",
      "author": "Julien Renoult",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Squalius_laietanus.jpg"
    }
  ],
  "crapet-de-roche": [
    {
      "file": "assets/species/crapet-de-roche.webp",
      "author": "Sam Stukel (USFWS)",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rock_Bass_(Ambloplites_rupestris).jpg"
    }
  ],
  "eperlan": [
    {
      "file": "assets/species/eperlan.webp",
      "author": "Thomas Pruss",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Osmerus_eperlanus.JPG"
    }
  ],
  "lamproie-de-riviere": [
    {
      "file": "assets/species/lamproie-de-riviere.webp",
      "author": "Andre Hosper",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lampetra_fluviatilis_26099057.jpg"
    }
  ],
  "loche-d-etang": [
    {
      "file": "assets/species/loche-d-etang.webp",
      "author": "George Chernilevsky",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Misgurnus_fossilis_2009_G1.jpg"
    }
  ],
  "lote-de-riviere": [
    {
      "file": "assets/species/lote-de-riviere.webp",
      "author": "Ákos Harka",
      "license": "CC BY 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lota_lota_Hungary.jpg"
    }
  ],
  "mulet-cabot": [
    {
      "file": "assets/species/mulet-cabot.webp",
      "author": "Bikerhiker75",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gro%C3%9Fkopfmeer%C3%A4sche_(Mugil_cephalus).jpg"
    }
  ],
  "mulet-dore": [
    {
      "file": "assets/species/mulet-dore.webp",
      "author": "Diego Delso",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Galupe_(Chelon_auratus),_Parque_natural_de_la_Arr%C3%A1bida,_Portugal,_2021-09-09,_DD_21.jpg"
    }
  ],
  "mulet-lippu": [
    {
      "file": "assets/species/mulet-lippu.webp",
      "author": "Diego Delso",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Muble_(Chelon_labrosus),_isla_de_Mouro,_Santander,_Espa%C3%B1a,_2019-08-15,_DD_88.jpg"
    }
  ],
  "goujon-ukraine": [
    {
      "file": "assets/species/goujon-ukraine.webp",
      "author": "Yuriy Kvach",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Romanogobio_vladykovi.jpg"
    }
  ],
  "vairon-basque": [
    {
      "file": "assets/species/vairon-basque.webp",
      "author": "David Perez (DPC)",
      "license": "CC BY 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Phoxinus_bigerri_01_by-dpc.jpg"
    }
  ],
  "vairon-du-languedoc": [
    {
      "file": "assets/species/vairon-du-languedoc.webp",
      "author": "Julien Renoult",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Phoxinus_septimaniae_519471402.jpg"
    }
  ],
  "vimbe": [
    {
      "file": "assets/species/vimbe.webp",
      "author": "Emőke Dénes",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cypriniformes_-_Vimba_vimba_-_1.jpg"
    }
  ],
  "goujon-occitan": [
    {
      "file": "assets/species/goujon-occitan.webp",
      "author": "Zakqary Roy (iNaturalist)",
      "license": "CC BY 4.0",
      "sourceUrl": "https://www.inaturalist.org/observations/193088388"
    }
  ],
  "vairon-de-garonne": [
    {
      "file": "assets/species/vairon-de-garonne.webp",
      "author": "Julien Renoult (iNaturalist)",
      "license": "CC BY 4.0",
      "sourceUrl": "https://www.inaturalist.org/observations/15443574"
    }
  ],
  "vairon-du-danube": [
    {
      "file": "assets/species/vairon-du-danube.webp",
      "author": "Adi Peter (iNaturalist)",
      "license": "CC BY 4.0",
      "sourceUrl": "https://www.inaturalist.org/observations/306268854"
    }
  ],
  "goujon-auvergne": [
    {
      "file": "assets/species/goujon-auvergne.webp",
      "author": "Julien Renoult (iNaturalist)",
      "license": "CC BY 4.0",
      "sourceUrl": "https://www.inaturalist.org/observations/126253900"
    }
  ],
  "vandoise-du-bearn": [
    {
      "file": "assets/species/vandoise-du-bearn.webp",
      "author": "Julien Renoult (iNaturalist)",
      "license": "CC BY 4.0",
      "sourceUrl": "https://www.inaturalist.org/observations/307110637"
    }
  ],
  "aphanius-de-corse": [
    {
      "file": "assets/species/aphanius-de-corse.webp",
      "author": "Gastcrf / Gastcrf at Greek Wikipedia",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Aphan.jpg"
    }
  ],
  "bar-commun": [
    {
      "file": "assets/species/bar-commun.webp",
      "author": "Andrea Quadrio",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dicentrarchus_labrax_23224415.jpg"
    }
  ],
  "blageon-italien": [
    {
      "file": "assets/species/blageon-italien.webp",
      "author": "Etrusko25",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Telestes_muticellus.jpg"
    }
  ],
  "breme-du-danube": [
    {
      "file": "assets/species/breme-du-danube.webp",
      "author": "[Marsigli, Danubius Pannonico-Mysicus], IV tab. 17",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Abramis_sapa_-_1726_-_Print_-_Iconographia_Zoologica_-_Special_Collections_University_of_Amsterdam_-_UBA01_IZ15000128.tif",
      "caption": "Illustration historique (Marsigli, 1726)"
    }
  ],
  "brochet-italien": [
    {
      "file": "assets/species/brochet-italien.webp",
      "author": "Etrusko25",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Esox_cisalpinus_(cropped).jpg"
    }
  ],
  "carpe-a-grosse-tete": [
    {
      "file": "assets/species/carpe-a-grosse-tete.webp",
      "author": "Original uploader was Carptracker at en.wikipedia",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bighead_carp_b.gif"
    }
  ],
  "chabot-d-auvergne": [
    {
      "file": "assets/species/chabot-d-auvergne.webp",
      "author": "Julien Renoult",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cottus_duranii_214190150.jpg"
    }
  ],
  "chabot-du-bearn": [
    {
      "file": "assets/species/chabot-du-bearn.webp",
      "author": "Julien Renoult",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Adour_sculpin_(cropped).jpg"
    }
  ],
  "chabot-du-lez": [
    {
      "file": "assets/species/chabot-du-lez.webp",
      "author": "Blé en Herbe",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chabot_du_Lez_(cropped).JPG"
    }
  ],
  "coregone-blanc": [
    {
      "file": "assets/species/coregone-blanc.webp",
      "author": "encyclopedia, \"Pieni Tietosanakirja\"",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Coregonus_albula_(Pieni).jpg"
    }
  ],
  "epirine-lippue": [
    {
      "file": "assets/species/epirine-lippue.webp",
      "author": "jujurenoult",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pachychilon_pictum_(cropped).jpg"
    }
  ],
  "gobie-a-taches-noires": [
    {
      "file": "assets/species/gobie-a-taches-noires.webp",
      "author": "Eric Engbretson, U.S. Fish and Wildlife Service",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Neogobius_melanostomus1.jpg"
    }
  ],
  "gobie-de-kessler": [
    {
      "file": "assets/species/gobie-de-kessler.webp",
      "author": "Piet Spaans",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:NeogobiusKessleriSide_7-9-2009_10-13-45_AM.JPG"
    }
  ],
  "gobie-demi-lune": [
    {
      "file": "assets/species/gobie-demi-lune.webp",
      "author": "FilipTomíček48",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hlava%C4%8Dka_polom%C4%9Bs%C3%AD%C4%8Dit%C3%A1.jpg"
    }
  ],
  "gobie-des-sables": [
    {
      "file": "assets/species/gobie-des-sables.webp",
      "author": "Joacim Näslund",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sand_goby_(Pomatoschistus_minutus)_Sweden.jpg"
    }
  ],
  "gobie-fluviatile": [
    {
      "file": "assets/species/gobie-fluviatile.webp",
      "author": "Yuriy Kvach",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Monkey_goby_male_1.jpg"
    }
  ],
  "gobie-tachete": [
    {
      "file": "assets/species/gobie-tachete.webp",
      "author": "Ove Glenjen",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:046-011_Pomatoschistus_microps_(cropped).JPG"
    }
  ],
  "goujon-de-l-adour": [
    {
      "file": "assets/species/goujon-de-l-adour.webp",
      "author": "David Perez",
      "license": "CC BY 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gobio_lozanoi_01_by-dpc.jpg"
    }
  ],
  "guppy": [
    {
      "file": "assets/species/guppy.webp",
      "author": "Sevan76",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alevins_guppy.PNG"
    }
  ],
  "joel": [
    {
      "file": "assets/species/joel.webp",
      "author": "Roberto Pillon",
      "license": "CC BY 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Atherina_boyeri_Sardinia.jpg"
    }
  ],
  "loche-a-grandes-ecailles": [
    {
      "file": "assets/species/loche-a-grandes-ecailles.webp",
      "author": "MaiMend",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Paramisgusnus_dabryanus_Dabry_de_Thiersant,_1872.png",
      "caption": "Illustration du holotype (Dabry de Thiersant, 1872)"
    }
  ],
  "loche-leopard": [
    {
      "file": "assets/species/loche-leopard.webp",
      "author": "Julien Renoult",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Barbatula_leoparda_01_(cropped).jpg"
    }
  ],
  "loche-transalpine": [
    {
      "file": "assets/species/loche-transalpine.webp",
      "author": "Etrusko25",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cobitis_bilineata_1_(cropped).jpg"
    }
  ],
  "mulet-sauteur": [
    {
      "file": "assets/species/mulet-sauteur.webp",
      "author": "Citron",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Liza_saliens.jpg"
    }
  ],
  "palee": [
    {
      "file": "assets/species/palee.webp",
      "author": "Ellicrum",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Coregonus_palaea.png"
    }
  ],
  "rotengle-italien": [
    {
      "file": "assets/species/rotengle-italien.webp",
      "author": "etrusko25",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Italian_rudd.jpg"
    }
  ],
  "saumon-rose": [
    {
      "file": "assets/species/saumon-rose.webp",
      "author": "Timothy Knepp",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pink_salmon_FWS.jpg"
    }
  ],
  "sterlet": [
    {
      "file": "assets/species/sterlet.webp",
      "author": "Karelj",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Acipenser_ruthenus_Prague_Vltava_1.jpg"
    }
  ],
  "syngnathe": [
    {
      "file": "assets/species/syngnathe.webp",
      "author": "Yuriy Kvach",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Syngnathus_abaster-23.jpg"
    }
  ],
  "tete-de-boule": [
    {
      "file": "assets/species/tete-de-boule.webp",
      "author": "Rankin1958",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fathead_Minnow_-_Breeding_Male.JPG"
    }
  ],
  "truite-corse": [
    {
      "file": "assets/species/truite-corse.webp",
      "author": "Novaculum",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Salmo_ghigii_Capodacqua_(cropped).jpg"
    }
  ],
  "vairon-italien": [
    {
      "file": "assets/species/vairon-italien.webp",
      "author": "jujurenoult",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Phoxinus_lumaireul_(cropped).jpg"
    }
  ],
  "esturgeon-siberien": [
    {
      "file": "assets/species/esturgeon-siberien.webp",
      "author": "Kovács András",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Acipenser_baerii-Lenai_tok.jpg"
    }
  ],
  "loche-asiatique": [
    {
      "file": "assets/species/loche-asiatique.webp",
      "author": "Naotake Murayama from San Francisco, CA, USA",
      "license": "CC BY 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Misgurnus_anguillicaudatus_(2678935266).jpg"
    }
  ],
  "loche-du-lez": [
    {
      "file": "assets/species/loche-du-lez.webp",
      "author": "David Perez",
      "license": "CC BY 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Barbatula_quignardi_01_by-dpc.jpg"
    }
  ],
  "truite-du-rhone": [
    {
      "file": "assets/species/truite-du-rhone.webp",
      "author": "Samuel GUIRAUDOU",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Salmo_rhodanensis_152902013.jpg"
    }
  ],
  "umbre-pygmee": [
    {
      "file": "assets/species/umbre-pygmee.webp",
      "author": "Ellen Edmonson and Hugh Chrisp",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Umbra_pygmaea.jpg"
    }
  ]
};

export const KNOT_MEDIA: Record<string, MediaEntry> = {
  "clinch": {
    "file": "assets/knots/clinch.webp",
    "author": "StromBer",
    "license": "CC BY-SA 2.0 DE",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:KlammerknotenLose.JPG"
  },
  "boucle": {
    "file": "assets/knots/boucle.webp",
    "author": "LadyofHats",
    "license": "Domaine public",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Surgeon's_Loop_knot.svg"
  },
  "texan": {
    "file": "assets/knots/texan.webp",
    "author": "Zachary635",
    "license": "CC BY 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Texas_Rig_Diagram.svg"
  }
};

export const KNOT_STEP_MEDIA: Record<string, MediaEntry[]> = {
  "sang": [
    {
      "file": "assets/knots-steps/sang-1.webp",
      "author": "Chris 73",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:BloodKnot_HowTo.jpg"
    }
  ],
  "albright": [
    {
      "file": "assets/knots-steps/albright-1.webp",
      "author": "LadyofHats (original) · retouché par Dfred",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Albright_knot_diagram_retouched.png"
    }
  ],
  "chaise": [
    {
      "file": "assets/knots-steps/chaise-1.webp",
      "author": "Luis Dantas",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bowline_in_four_steps.png"
    }
  ],
  "boucle": [
    {
      "file": "assets/knots-steps/boucle-1.webp",
      "author": "LadyofHats",
      "license": "Domaine public",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Surgeon's_Loop_knot.svg"
    }
  ]
};

export const RECIPE_MEDIA: Record<string, MediaEntry> = {
  "quenelles-de-brochet": {
    "file": "assets/recipes/quenelles-de-brochet.webp",
    "author": "Fryke27",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Quenelle_de_brochet_sauce_Nantua.jpg"
  }
};

export const TECHNIQUE_MEDIA: Record<string, MediaEntry> = {};

export const GEAR_MEDIA: Record<string, MediaEntry> = {
  "leurre-souple": {
    "file": "assets/gear/leurre-souple.webp",
    "author": "George Chernilevsky",
    "license": "Domaine public",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jig-Twister_lure_2009_G1.jpg"
  },
  "poisson-nageur": {
    "file": "assets/gear/poisson-nageur.webp",
    "author": "Ra Boe",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Angeln_zubehoer_wobbler_01.jpg"
  },
  "cuiller-tournante": {
    "file": "assets/gear/cuiller-tournante.webp",
    "author": "Frank-Christian Baum",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Spinner_(K%C3%B6der).jpg"
  },
  "cuiller-ondulante": {
    "file": "assets/gear/cuiller-ondulante.webp",
    "author": "Petey21",
    "license": "Domaine public",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Copper_fishing_lure.jpg"
  },
  "spinnerbait": {
    "file": "assets/gear/spinnerbait.webp",
    "author": "Danndorfer1914",
    "license": "CC0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Spinnerbait.png"
  },
  "popper-stickbait": {
    "file": "assets/gear/popper-stickbait.webp",
    "author": "Ikkionline",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Poper.JPG"
  },
  "jig": {
    "file": "assets/gear/jig.webp",
    "author": "Mike Cline",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:SaltwaterJigHook.jpg"
  },
  "ver-de-terre": {
    "file": "assets/gear/ver-de-terre.webp",
    "author": "Michael Linnenbach",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lumbricus_terrestris.JPG"
  },
  "asticot": {
    "file": "assets/gear/asticot.webp",
    "author": "Donald Trung Quoc Don",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Maggots_for_fishing,_Winschoten_(2020)_01.jpg"
  },
  "teigne": {
    "file": "assets/gear/teigne.webp",
    "author": "ImagePerson",
    "license": "CC BY 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mealworm_Beetle_Tenebrio_molitor_larva_04.jpg"
  },
  "mais-doux": {
    "file": "assets/gear/mais-doux.webp",
    "author": "Gaurav Dhwaj Khadka",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Corn_Kernel.jpg"
  },
  "bouillette": {
    "file": "assets/gear/bouillette.webp",
    "author": "Davem0sad",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Selection_of_Boilies.jpg"
  },
  "ver-marin": {
    "file": "assets/gear/ver-marin.webp",
    "author": "Ria Wagemaker / Ecomare",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ecomare_-_wadpier_in_hand_(wadpier-familieprogramma-krassekeet-1348-rw).jpg"
  },
  "nylon": {
    "file": "assets/gear/nylon.webp",
    "author": "Bernhard Kuemel (Darsie42)",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fischerknoten_auf_Angelleine_lose.jpg"
  },
  "tresse": {
    "file": "assets/gear/tresse.webp",
    "author": "George Chernilevsky",
    "license": "CC BY 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fishing_lines_2025_G1.jpg"
  }
};
