// GENERATED by scripts/fetch-images.mjs — do not edit by hand.
// Each entry points to a locally-embedded image plus its licence attribution.
// Only free licences are accepted (CC0 / Public domain / CC BY / CC BY-SA).

export interface MediaEntry {
  file: string; // path under public/, e.g. "assets/species/sandre.webp"
  author: string;
  license: string;
  sourceUrl: string;
}

export const SPECIES_MEDIA: Record<string, MediaEntry> = {
  "sandre": {
    "file": "assets/species/sandre.webp",
    "author": "Tylwyth Eldar",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sandre_(Sander_lucioperca).jpg"
  },
  "brochet": {
    "file": "assets/species/brochet.webp",
    "author": "Gilles San Martin",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Esox_lucius_-_Brochet_-_Northern_pike.jpg"
  },
  "perche": {
    "file": "assets/species/perche.webp",
    "author": "Karelj",
    "license": "Domaine public",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Perca_fluviatilis_Prague_Vltava_2.jpg"
  },
  "black-bass": {
    "file": "assets/species/black-bass.webp",
    "author": "USFWS Mountain Prairie",
    "license": "Domaine public",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Largemouth_Bass_(Micropterus_salmoides)_(53118577249)_(cropped).jpg"
  },
  "silure": {
    "file": "assets/species/silure.webp",
    "author": "Dieter Florian",
    "license": "CC BY-SA 3.0 DE",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Silurus_glanis_02.jpg"
  },
  "gremille": {
    "file": "assets/species/gremille.webp",
    "author": "Tiit Hunt",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gymnocephalus_cernuus_P%C3%A4rnu_River_Estonia_2010-01-06.jpg"
  },
  "carpe": {
    "file": "assets/species/carpe.webp",
    "author": "Karelj",
    "license": "Domaine public",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Caprinus_carpio_Prague_Vltava_1.jpg"
  },
  "gardon": {
    "file": "assets/species/gardon.webp",
    "author": "kallerna",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Common_Roach.JPG"
  },
  "barbeau": {
    "file": "assets/species/barbeau.webp",
    "author": "Pmau",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Barbus_barbus_img_33502.jpg"
  },
  "carassin": {
    "file": "assets/species/carassin.webp",
    "author": "U.S. Geological Survey",
    "license": "Domaine public",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Carassius_carassius.jpg"
  },
  "rotengle": {
    "file": "assets/species/rotengle.webp",
    "author": "Paul Korecky",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2017-07-02_AT_Wien_13_Hietzing,_Tiergarten_Sch%C3%B6nbrunn,_Scardinius_erythrophthalmus_(49897346508).jpg"
  },
  "truite-fario": {
    "file": "assets/species/truite-fario.webp",
    "author": "Gilles San Martin",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Salmo_trutta_fario_-_Truite_fario_-_Brown_trout.jpg"
  },
  "truite-arc-en-ciel": {
    "file": "assets/species/truite-arc-en-ciel.webp",
    "author": "Liquid Art",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rainbow_Trout_(Oncorhynchus_mykiss).jpg"
  },
  "perche-soleil": {
    "file": "assets/species/perche-soleil.webp",
    "author": "Cephas",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lepomis_gibbosus_PAQ.jpg"
  },
  "poisson-chat": {
    "file": "assets/species/poisson-chat.webp",
    "author": "George Chernilevsky",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ameiurus_melas_2021_G1.jpg"
  },
  "breme": {
    "file": "assets/species/breme.webp",
    "author": "Karelj",
    "license": "Domaine public",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Abramis_brama_Prague_Vltava_1.jpg"
  },
  "tanche": {
    "file": "assets/species/tanche.webp",
    "author": "Pavel Kotrc",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tinca_tinca.jpg"
  },
  "ablette": {
    "file": "assets/species/ablette.webp",
    "author": "David Perez (DPC)",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alburnus_alburnus_01_by-dpc.jpg"
  },
  "chevesne": {
    "file": "assets/species/chevesne.webp",
    "author": "Karelj",
    "license": "Domaine public",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Squalius_cephalus_Prague_Vltava_1.jpg"
  },
  "hotu": {
    "file": "assets/species/hotu.webp",
    "author": "André Karwath (Aka)",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chondrostoma_nasus_(aka).jpg"
  },
  "goujon": {
    "file": "assets/species/goujon.webp",
    "author": "Karelj",
    "license": "Domaine public",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gobio_gobio_Prague_Vltava_1.jpg"
  },
  "ombre": {
    "file": "assets/species/ombre.webp",
    "author": "High Plains Grifter",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Grayling_Thymallus_thymallus.JPG"
  },
  "omble-fontaine": {
    "file": "assets/species/omble-fontaine.webp",
    "author": "Derek Ramsey (Ram-Man)",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Brook_Trout_Salvelinus_fontinalis_2900px.jpg"
  },
  "anguille": {
    "file": "assets/species/anguille.webp",
    "author": "GerardM",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Anguilla_anguilla.jpg"
  },
  "vandoise": {
    "file": "assets/species/vandoise.webp",
    "author": "Viridiflavus",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:LeuciscusLeuciscusSerpeling17.JPG"
  },
  "breme-bordeliere": {
    "file": "assets/species/breme-bordeliere.webp",
    "author": "Algirdas",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Blicca_bjoerkna.jpg"
  },
  "spirlin": {
    "file": "assets/species/spirlin.webp",
    "author": "Gilles San Martin",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alburnoides_bipunctatus.jpg"
  },
  "able-de-heckel": {
    "file": "assets/species/able-de-heckel.webp",
    "author": "Christian Fischer",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:LeucaspiusDelineatus1.jpg"
  },
  "ide-melanote": {
    "file": "assets/species/ide-melanote.webp",
    "author": "Piet Spaans",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:LeuciscusIdus.JPG"
  },
  "blageon": {
    "file": "assets/species/blageon.webp",
    "author": "Harka Akos",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Telestes_souffia.jpg"
  },
  "toxostome": {
    "file": "assets/species/toxostome.webp",
    "author": "Julien Renoult",
    "license": "CC BY 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Parachondrostoma_toxostoma.jpg"
  },
  "barbeau-meridional": {
    "file": "assets/species/barbeau-meridional.webp",
    "author": "Wikiwiki",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Barbus_meridionalis.jpg"
  },
  "carassin-argente": {
    "file": "assets/species/carassin-argente.webp",
    "author": "George Chernilevsky",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Carassius_gibelio_2008_G2.jpg"
  },
  "poisson-rouge": {
    "file": "assets/species/poisson-rouge.webp",
    "author": "Alyssachanpc",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Carassius_auratus_0045-1.jpg"
  },
  "amour-blanc": {
    "file": "assets/species/amour-blanc.webp",
    "author": "Dezidor",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ctenopharyngodon_idella.jpg"
  },
  "pseudorasbora": {
    "file": "assets/species/pseudorasbora.webp",
    "author": "Piet Spaans",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:PseudorasboraParva2.JPG"
  },
  "vairon": {
    "file": "assets/species/vairon.webp",
    "author": "Pmau",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Phoxinus_phoxinus_img_33481.jpg"
  },
  "omble-chevalier": {
    "file": "assets/species/omble-chevalier.webp",
    "author": "Saibling",
    "license": "Domaine public",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Salvelinusalpinus.jpg"
  },
  "cristivomer": {
    "file": "assets/species/cristivomer.webp",
    "author": "NOAA / GLERL",
    "license": "Domaine public",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lake_Trout_GLERL.jpg"
  },
  "saumon-atlantique": {
    "file": "assets/species/saumon-atlantique.webp",
    "author": "NOAA / GLERL",
    "license": "Domaine public",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Salmo_salar_GLERL_1.jpg"
  },
  "coregone-lavaret": {
    "file": "assets/species/coregone-lavaret.webp",
    "author": "Apple2000",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Coregonus_lavaretus_maraena_1.jpg"
  },
  "huchon": {
    "file": "assets/species/huchon.webp",
    "author": "Harald Peki",
    "license": "Attribution (libre)",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hucho_hucho.jpg"
  },
  "truite-de-mer": {
    "file": "assets/species/truite-de-mer.webp",
    "author": "Anne Blindheim / Lars Olaf Simonsen",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Salmo_trutta_trutta_retouched.jpg"
  },
  "brochet-aquitain": {
    "file": "assets/species/brochet-aquitain.webp",
    "author": "MillaTom",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hecht.jpg"
  },
  "black-bass-petite-bouche": {
    "file": "assets/species/black-bass-petite-bouche.webp",
    "author": "Eric Engbretson (USFWS)",
    "license": "Domaine public",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Micropterus_dolomieu.jpg"
  },
  "aspe": {
    "file": "assets/species/aspe.webp",
    "author": "Jenny Glans",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Aspius_aspius.jpg"
  },
  "grande-alose": {
    "file": "assets/species/grande-alose.webp",
    "author": "I. Cheret & L. Metral (Ifremer)",
    "license": "CC BY 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alose_vraie_(Alosa_alosa)_(Ifremer_00680-79165).jpg"
  },
  "alose-feinte-atlantique": {
    "file": "assets/species/alose-feinte-atlantique.webp",
    "author": "Hans Hillewaert",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alosa_fallax.jpg"
  },
  "lamproie-marine": {
    "file": "assets/species/lamproie-marine.webp",
    "author": "Emery Lee (USFWS)",
    "license": "Domaine public",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sea_lamprey_petromyzon_marinus.jpg"
  },
  "lamproie-de-planer": {
    "file": "assets/species/lamproie-de-planer.webp",
    "author": "Julien Renoult",
    "license": "CC BY 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lampetra_planeri.jpg"
  },
  "esturgeon-europeen": {
    "file": "assets/species/esturgeon-europeen.webp",
    "author": "Aah-Yeah",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:St%C3%B6r_Sturgeon.jpg"
  },
  "mulet-porc": {
    "file": "assets/species/mulet-porc.webp",
    "author": "etrusko25",
    "license": "CC BY 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chelon_ramada_Italy.jpg"
  },
  "flet": {
    "file": "assets/species/flet.webp",
    "author": "Holger Krisp",
    "license": "CC BY 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Flunder_Platichthys_flesus.jpg"
  },
  "epinoche": {
    "file": "assets/species/epinoche.webp",
    "author": "Gilles San Martin",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gasterosteus_aculeatus_-_Epinoche_-_Three-spined_stickleback.jpg"
  },
  "epinochette": {
    "file": "assets/species/epinochette.webp",
    "author": "Julien Renoult",
    "license": "CC BY 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pungitius_laevis.jpg"
  },
  "loche-franche": {
    "file": "assets/species/loche-franche.webp",
    "author": "OpenCage",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Barbatula_barbatula_by_OpenCage.jpg"
  },
  "loche-de-riviere": {
    "file": "assets/species/loche-de-riviere.webp",
    "author": "Ron Offermans",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cobitis_taenia.jpg"
  },
  "chabot-commun": {
    "file": "assets/species/chabot-commun.webp",
    "author": "\"D\" (de.wikipedia)",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cottus_gobio_-_Groppe_1.jpg"
  },
  "apron-du-rhone": {
    "file": "assets/species/apron-du-rhone.webp",
    "author": "Proche",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Zingel_asper.JPG"
  },
  "bouviere": {
    "file": "assets/species/bouviere.webp",
    "author": "Viridiflavus",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rhodeus_amarus.jpg"
  },
  "gambusie": {
    "file": "assets/species/gambusie.webp",
    "author": "etrusko25",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gambusia_holbrooki_1.jpg"
  }
};

export const KNOT_MEDIA: Record<string, MediaEntry> = {
  "clinch": {
    "file": "assets/knots/clinch.webp",
    "author": "StromBer",
    "license": "CC BY-SA 2.0 DE",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:KlammerknotenLose.JPG"
  },
  "palomar": {
    "file": "assets/knots/palomar.webp",
    "author": "Vaughan Pratt",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:PalomarKnotSequence.jpg"
  },
  "boucle": {
    "file": "assets/knots/boucle.webp",
    "author": "LadyofHats",
    "license": "Domaine public",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Surgeon's_Loop_knot.svg"
  },
  "texan": {
    "file": "assets/knots/texan.webp",
    "author": "Zachary635",
    "license": "CC BY 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Texas_Rig_Diagram.svg"
  }
};

export const RECIPE_MEDIA: Record<string, MediaEntry> = {
  "quenelles-de-brochet": {
    "file": "assets/recipes/quenelles-de-brochet.webp",
    "author": "Fryke27",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Quenelle_de_brochet_sauce_Nantua.jpg"
  }
};

export const TECHNIQUE_MEDIA: Record<string, MediaEntry> = {};
