// GENERATED by scripts/build-base-species.mjs — do not edit by hand.
// "Base" coverage: taxonomy + regulation-by-rule + bio stub for species not yet
// hand-curated. Merged after the curated SPECIES so the whole national list appears.
import type { Species } from "../types";

export const BASE_SPECIES: Species[] = [
  {
    "id": "able-de-heckel",
    "name": "Able de Heckel",
    "latin": "Leucaspius delineatus",
    "group": "cyprinides",
    "family": "Leuciscidae",
    "cdNom": "67286",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Techniques",
          "Pêche au coup, feeder, à l'anglaise, avec amorçage"
        ],
        [
          "Appâts",
          "Asticot, ver, graines, maïs, pain"
        ],
        [
          "Postes",
          "Eaux calmes, bordures, fonds nourriciers"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Leuciscidae"
        ],
        [
          "Remarque",
          "Très petit (< 9 cm), ligne latérale incomplète ; petites eaux stagnantes, en régression."
        ]
      ]
    }
  },
  {
    "id": "alose-feinte-atlantique",
    "name": "Alose feinte atlantique",
    "latin": "Alosa fallax",
    "group": "migrateurs",
    "family": "Clupeidae",
    "cdNom": "66996",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "protected": true,
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Espèce protégée / menacée — remise à l'eau"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21 · statut de protection (voir remarque)"
    },
    "fish": {
      "rows": [
        [
          "À savoir",
          "Espèce protégée ou menacée — à ne pas cibler."
        ],
        [
          "Bon geste",
          "Relâchez immédiatement toute capture accidentelle, mains mouillées."
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Clupeidae"
        ],
        [
          "Remarque",
          "Œufs et frayères protégés + Directive Habitats ; pêche très restreinte selon bassin — à vérifier."
        ]
      ]
    }
  },
  {
    "id": "alose-feinte-mediterraneenne",
    "name": "Alose feinte méditerranéenne",
    "latin": "Alosa agone",
    "group": "migrateurs",
    "family": "Clupeidae",
    "cdNom": "66964",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "protected": true,
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Espèce protégée / menacée — remise à l'eau"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21 · statut de protection (voir remarque)"
    },
    "fish": {
      "rows": [
        [
          "À savoir",
          "Espèce protégée ou menacée — à ne pas cibler."
        ],
        [
          "Bon geste",
          "Relâchez immédiatement toute capture accidentelle, mains mouillées."
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Clupeidae"
        ],
        [
          "Remarque",
          "Forme méditerranéenne (bassin rhodanien), Directive Habitats ; pêche restreinte — à vérifier."
        ]
      ]
    }
  },
  {
    "id": "amour-blanc",
    "name": "Amour blanc (carpe herbivore)",
    "latin": "Ctenopharyngodon idella",
    "group": "cyprinides",
    "family": "Cyprinidae",
    "cdNom": "67246",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Techniques",
          "Pêche au coup, feeder, à l'anglaise, avec amorçage"
        ],
        [
          "Appâts",
          "Asticot, ver, graines, maïs, pain"
        ],
        [
          "Postes",
          "Eaux calmes, bordures, fonds nourriciers"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Cyprinidae"
        ],
        [
          "Remarque",
          "Introduit d'Asie pour désherber ; ne se reproduit pas naturellement en France (empoissonné)."
        ]
      ]
    }
  },
  {
    "id": "apron-du-rhone",
    "name": "Apron du Rhône",
    "latin": "Zingel asper",
    "group": "autres",
    "family": "Percidae",
    "cdNom": "69378",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "protected": true,
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Espèce protégée / menacée — remise à l'eau"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21 · statut de protection (voir remarque)"
    },
    "fish": {
      "rows": [
        [
          "À savoir",
          "Espèce protégée ou menacée — à ne pas cibler."
        ],
        [
          "Bon geste",
          "Relâchez immédiatement toute capture accidentelle, mains mouillées."
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Percidae"
        ],
        [
          "Remarque",
          "PROTÉGÉ et en danger critique (arrêté 8 déc. 1988 + Directive Habitats + Berne) ; endémique rhodanien, capture à proscrire, remise à l'eau immédiate."
        ]
      ]
    }
  },
  {
    "id": "aspe",
    "name": "Aspe",
    "latin": "Leuciscus aspius",
    "group": "carnassiers",
    "family": "Leuciscidae",
    "cdNom": "200255",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Techniques",
          "Leurres (souples, poissons-nageurs, cuiller), pêche au vif"
        ],
        [
          "Postes",
          "Cassures, obstacles immergés, herbiers, veines de courant"
        ],
        [
          "Moment",
          "Souvent plus actif à l'aube et au crépuscule"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Leuciscidae"
        ],
        [
          "Remarque",
          "Seul cyprinidé franchement piscivore ; ex-Aspius aspius. En expansion (Rhin, introductions)."
        ]
      ]
    }
  },
  {
    "id": "barbeau-meridional",
    "name": "Barbeau méridional",
    "latin": "Barbus meridionalis",
    "group": "cyprinides",
    "family": "Cyprinidae",
    "cdNom": "67179",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "protected": true,
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Espèce protégée / menacée — remise à l'eau"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21 · statut de protection (voir remarque)"
    },
    "fish": {
      "rows": [
        [
          "À savoir",
          "Espèce protégée ou menacée — à ne pas cibler."
        ],
        [
          "Bon geste",
          "Relâchez immédiatement toute capture accidentelle, mains mouillées."
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Cyprinidae"
        ],
        [
          "Remarque",
          "Protégé (arrêté 8 déc. 1988) + Directive Habitats An. II ; petit barbeau du Sud (barbeau truité). Remise à l'eau."
        ]
      ]
    }
  },
  {
    "id": "black-bass-petite-bouche",
    "name": "Black-bass à petite bouche",
    "latin": "Micropterus dolomieu",
    "group": "carnassiers",
    "family": "Centrarchidae",
    "cdNom": "69344",
    "maille": "30 cm",
    "mailleSub": "national (R436-18)",
    "quota": "—",
    "quotaSub": "carnassiers cumulés",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "30 cm (national, R436-18)"
        ],
        [
          "Quota",
          "Compte dans les 3 carnassiers/jour (R436-21)"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Techniques",
          "Leurres (souples, poissons-nageurs, cuiller), pêche au vif"
        ],
        [
          "Postes",
          "Cassures, obstacles immergés, herbiers, veines de courant"
        ],
        [
          "Moment",
          "Souvent plus actif à l'aube et au crépuscule"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Centrarchidae"
        ],
        [
          "Remarque",
          "Introduit ; présence très localisée — établissement à vérifier ; maille 0,30 m."
        ]
      ]
    }
  },
  {
    "id": "blageon",
    "name": "Blageon",
    "latin": "Telestes souffia",
    "group": "cyprinides",
    "family": "Leuciscidae",
    "cdNom": "67335",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "protected": true,
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Espèce protégée / menacée — remise à l'eau"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21 · statut de protection (voir remarque)"
    },
    "fish": {
      "rows": [
        [
          "À savoir",
          "Espèce protégée ou menacée — à ne pas cibler."
        ],
        [
          "Bon geste",
          "Relâchez immédiatement toute capture accidentelle, mains mouillées."
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Leuciscidae"
        ],
        [
          "Remarque",
          "Directive Habitats An. II (protection d'habitat) ; bande latérale sombre ; Rhône, Est/Sud-Est. Remise à l'eau conseillée."
        ]
      ]
    }
  },
  {
    "id": "blennie-fluviatile",
    "name": "Blennie fluviatile",
    "latin": "Salariopsis fluviatilis",
    "group": "autres",
    "family": "Blenniidae",
    "cdNom": "1005993",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "protected": true,
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Espèce protégée / menacée — remise à l'eau"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21 · statut de protection (voir remarque)"
    },
    "fish": {
      "rows": [
        [
          "À savoir",
          "Espèce protégée ou menacée — à ne pas cibler."
        ],
        [
          "Bon geste",
          "Relâchez immédiatement toute capture accidentelle, mains mouillées."
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Blenniidae"
        ],
        [
          "Remarque",
          "Œufs et frayères protégés (arrêté 8 déc. 1988) ; seule blennie d'eau douce, bassins méditerranéens — remise à l'eau."
        ]
      ]
    }
  },
  {
    "id": "bouviere",
    "name": "Bouvière",
    "latin": "Rhodeus amarus",
    "group": "autres",
    "family": "Cyprinidae",
    "cdNom": "67420",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "protected": true,
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Espèce protégée / menacée — remise à l'eau"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21 · statut de protection (voir remarque)"
    },
    "fish": {
      "rows": [
        [
          "À savoir",
          "Espèce protégée ou menacée — à ne pas cibler."
        ],
        [
          "Bon geste",
          "Relâchez immédiatement toute capture accidentelle, mains mouillées."
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Cyprinidae"
        ],
        [
          "Remarque",
          "Œufs et frayères protégés + Directive Habitats ; pond dans les moules d'eau douce — remise à l'eau."
        ]
      ]
    }
  },
  {
    "id": "breme-bordeliere",
    "name": "Brème bordelière",
    "latin": "Blicca bjoerkna",
    "group": "cyprinides",
    "family": "Leuciscidae",
    "cdNom": "67203",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Techniques",
          "Pêche au coup, feeder, à l'anglaise, avec amorçage"
        ],
        [
          "Appâts",
          "Asticot, ver, graines, maïs, pain"
        ],
        [
          "Postes",
          "Eaux calmes, bordures, fonds nourriciers"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Leuciscidae"
        ],
        [
          "Remarque",
          "Plus petite que la brème commune, base des pectorales rougeâtre."
        ]
      ]
    }
  },
  {
    "id": "brochet-aquitain",
    "name": "Brochet aquitain",
    "latin": "Esox aquitanicus",
    "group": "carnassiers",
    "family": "Esocidae",
    "cdNom": "781090",
    "maille": "50 cm",
    "mailleSub": "national (R436-18)",
    "quota": "—",
    "quotaSub": "carnassiers cumulés",
    "season": "brochet",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "50 cm (national, R436-18)"
        ],
        [
          "Quota",
          "Compte dans les 3 carnassiers/jour (2 brochets max, R436-21)"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "Fermeture spécifique brochet (voir réglementation)"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Techniques",
          "Leurres (souples, poissons-nageurs, cuiller), pêche au vif"
        ],
        [
          "Postes",
          "Cassures, obstacles immergés, herbiers, veines de courant"
        ],
        [
          "Moment",
          "Souvent plus actif à l'aube et au crépuscule"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Esocidae"
        ],
        [
          "Remarque",
          "Endémique du Sud-Ouest, décrit en 2014 ; même réglementation que le brochet ; enjeu de conservation — à vérifier."
        ]
      ]
    }
  },
  {
    "id": "carassin-argente",
    "name": "Carassin argenté (gibèle)",
    "latin": "Carassius gibelio",
    "group": "cyprinides",
    "family": "Cyprinidae",
    "cdNom": "67210",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Techniques",
          "Pêche au coup, feeder, à l'anglaise, avec amorçage"
        ],
        [
          "Appâts",
          "Asticot, ver, graines, maïs, pain"
        ],
        [
          "Postes",
          "Eaux calmes, bordures, fonds nourriciers"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Cyprinidae"
        ],
        [
          "Remarque",
          "Introduit envahissant (gynogenèse), mais pas sur la liste R432-5. Considéré exotique envahissant écologiquement."
        ]
      ]
    }
  },
  {
    "id": "poisson-rouge",
    "name": "Carassin doré (poisson rouge)",
    "latin": "Carassius auratus",
    "group": "cyprinides",
    "family": "Cyprinidae",
    "cdNom": "67208",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Techniques",
          "Pêche au coup, feeder, à l'anglaise, avec amorçage"
        ],
        [
          "Appâts",
          "Asticot, ver, graines, maïs, pain"
        ],
        [
          "Postes",
          "Eaux calmes, bordures, fonds nourriciers"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Cyprinidae"
        ],
        [
          "Remarque",
          "Introduit (lâchers d'aquarium/bassin) ; établi localement."
        ]
      ]
    }
  },
  {
    "id": "carpe-argentee",
    "name": "Carpe argentée",
    "latin": "Hypophthalmichthys molitrix",
    "group": "cyprinides",
    "family": "Cyprinidae",
    "cdNom": "67275",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Techniques",
          "Pêche au coup, feeder, à l'anglaise, avec amorçage"
        ],
        [
          "Appâts",
          "Asticot, ver, graines, maïs, pain"
        ],
        [
          "Postes",
          "Eaux calmes, bordures, fonds nourriciers"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Cyprinidae"
        ],
        [
          "Remarque",
          "Introduit d'Asie (aquaculture/plans d'eau) ; reproduction naturelle non établie. À vérifier."
        ]
      ]
    }
  },
  {
    "id": "chabot-commun",
    "name": "Chabot commun",
    "latin": "Cottus gobio",
    "group": "autres",
    "family": "Cottidae",
    "cdNom": "69182",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "cat1",
    "depth": "base",
    "protected": true,
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Espèce protégée / menacée — remise à l'eau"
        ],
        [
          "Période",
          "1ʳᵉ cat. : 2ᵉ samedi de mars → 3ᵉ dimanche de septembre"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21 · statut de protection (voir remarque)"
    },
    "fish": {
      "rows": [
        [
          "À savoir",
          "Espèce protégée ou menacée — à ne pas cibler."
        ],
        [
          "Bon geste",
          "Relâchez immédiatement toute capture accidentelle, mains mouillées."
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Cottidae"
        ],
        [
          "Remarque",
          "Directive Habitats (intérêt communautaire) ; complexe d'espèces — remise à l'eau conseillée."
        ]
      ]
    }
  },
  {
    "id": "chabot-fluviatile",
    "name": "Chabot fluviatile",
    "latin": "Cottus perifretum",
    "group": "autres",
    "family": "Cottidae",
    "cdNom": "416658",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "cat1",
    "depth": "base",
    "protected": true,
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Espèce protégée / menacée — remise à l'eau"
        ],
        [
          "Période",
          "1ʳᵉ cat. : 2ᵉ samedi de mars → 3ᵉ dimanche de septembre"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21 · statut de protection (voir remarque)"
    },
    "fish": {
      "rows": [
        [
          "À savoir",
          "Espèce protégée ou menacée — à ne pas cibler."
        ],
        [
          "Bon geste",
          "Relâchez immédiatement toute capture accidentelle, mains mouillées."
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Cottidae"
        ],
        [
          "Remarque",
          "Issu de la révision du complexe Cottus gobio ; Directive Habitats — remise à l'eau conseillée."
        ]
      ]
    }
  },
  {
    "id": "chevesne-catalan",
    "name": "Chevesne catalan",
    "latin": "Squalius laietanus",
    "group": "cyprinides",
    "family": "Leuciscidae",
    "cdNom": "459646",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Techniques",
          "Pêche au coup, feeder, à l'anglaise, avec amorçage"
        ],
        [
          "Appâts",
          "Asticot, ver, graines, maïs, pain"
        ],
        [
          "Postes",
          "Eaux calmes, bordures, fonds nourriciers"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Leuciscidae"
        ],
        [
          "Remarque",
          "Endémique catalan ; France limitée aux Pyrénées-Orientales (Tech, Têt)."
        ]
      ]
    }
  },
  {
    "id": "coregone-lavaret",
    "name": "Corégone / lavaret / féra",
    "latin": "Coregonus lavaretus",
    "group": "salmonides",
    "family": "Salmonidae",
    "cdNom": "67862",
    "maille": "30 cm",
    "mailleSub": "national (R436-18)",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "30 cm (national, R436-18)"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Techniques",
          "Pêche à la mouche, au toc, petits leurres (cuiller, vairon)"
        ],
        [
          "Milieu",
          "Eaux vives, fraîches et oxygénées (1ʳᵉ catégorie)"
        ],
        [
          "Éthique",
          "Souvent no-kill / quotas stricts — vérifiez localement"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Salmonidae"
        ],
        [
          "Remarque",
          "Complexe lavaret/féra ; grands lacs (Léman, Bourget, Aiguebelette, 2ᵉ cat.) : pas de fermeture 1ʳᵉ catégorie ; période fixée par arrêté préfectoral (souvent fermeture hivernale de fraie). Maille 0,30 m."
        ]
      ]
    }
  },
  {
    "id": "cristivomer",
    "name": "Cristivomer (touladi)",
    "latin": "Salvelinus namaycush",
    "group": "salmonides",
    "family": "Salmonidae",
    "cdNom": "67819",
    "maille": "35 cm",
    "mailleSub": "national (R436-18)",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "35 cm (national, R436-18)"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Techniques",
          "Pêche à la mouche, au toc, petits leurres (cuiller, vairon)"
        ],
        [
          "Milieu",
          "Eaux vives, fraîches et oxygénées (1ʳᵉ catégorie)"
        ],
        [
          "Éthique",
          "Souvent no-kill / quotas stricts — vérifiez localement"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Salmonidae"
        ],
        [
          "Remarque",
          "Introduit (Amérique du Nord) ; grands lacs alpins (2ᵉ cat.) : la fermeture 1ʳᵉ catégorie ne s'applique pas ; période fixée par arrêté préfectoral. Maille nationale 0,35 m (R436-18)."
        ]
      ]
    }
  },
  {
    "id": "epinoche",
    "name": "Épinoche à trois épines",
    "latin": "Gasterosteus aculeatus",
    "group": "autres",
    "family": "Gasterosteidae",
    "cdNom": "69010",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Statut",
          "Petite espèce, rarement ciblée ; parfois utilisée comme vif"
        ],
        [
          "Postes",
          "Fonds et bordures des rivières et ruisseaux"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Gasterosteidae"
        ],
        [
          "Remarque",
          "Petit poisson (~5–7 cm) non protégé ; bio-indicateur, mâle bâtisseur de nid."
        ]
      ]
    }
  },
  {
    "id": "epinochette",
    "name": "Épinochette",
    "latin": "Pungitius laevis",
    "group": "autres",
    "family": "Gasterosteidae",
    "cdNom": "200259",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Statut",
          "Petite espèce, rarement ciblée ; parfois utilisée comme vif"
        ],
        [
          "Postes",
          "Fonds et bordures des rivières et ruisseaux"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Gasterosteidae"
        ],
        [
          "Remarque",
          "Petit gastérostéidé (~4–6 cm) non protégé."
        ]
      ]
    }
  },
  {
    "id": "esturgeon-europeen",
    "name": "Esturgeon européen",
    "latin": "Acipenser sturio",
    "group": "migrateurs",
    "family": "Acipenseridae",
    "cdNom": "66775",
    "maille": "Interdit",
    "mailleSub": "voir réglementation",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "protected": true,
    "reg": {
      "rows": [
        [
          "Maille",
          "Interdit"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Espèce protégée / menacée — remise à l'eau"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21 · statut de protection (voir remarque)"
    },
    "fish": {
      "rows": [
        [
          "À savoir",
          "Espèce protégée ou menacée — à ne pas cibler."
        ],
        [
          "Bon geste",
          "Relâchez immédiatement toute capture accidentelle, mains mouillées."
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Acipenseridae"
        ],
        [
          "Remarque",
          "PÊCHE TOTALEMENT INTERDITE — protection stricte (Directive Habitats An. IV, Berne, CITES) ; en danger critique, remise à l'eau immédiate obligatoire."
        ]
      ]
    }
  },
  {
    "id": "flet",
    "name": "Flet d'Europe",
    "latin": "Platichthys flesus",
    "group": "migrateurs",
    "family": "Pleuronectidae",
    "cdNom": "70554",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Techniques",
          "Selon l'espèce ; pêche souvent très réglementée ou fermée"
        ],
        [
          "Rappel",
          "Nombreux migrateurs protégés ou sous quota — vérifiez l'arrêté"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Pleuronectidae"
        ],
        [
          "Remarque",
          "Poisson plat amphihalin remontant en eau douce ; réglementation pêche maritime (maille selon façade)."
        ]
      ]
    }
  },
  {
    "id": "gambusie",
    "name": "Gambusie",
    "latin": "Gambusia holbrooki",
    "group": "autres",
    "family": "Poeciliidae",
    "cdNom": "68827",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Statut",
          "Petite espèce, rarement ciblée ; parfois utilisée comme vif"
        ],
        [
          "Postes",
          "Fonds et bordures des rivières et ruisseaux"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Poeciliidae"
        ],
        [
          "Remarque",
          "Exotique introduite (lutte anti-moustiques) ; non listée R432-5 au national — à vérifier localement."
        ]
      ]
    }
  },
  {
    "id": "goujon-auvergne",
    "name": "Goujon d'Auvergne",
    "latin": "Gobio alverniae",
    "group": "cyprinides",
    "family": "Gobionidae",
    "cdNom": "388244",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Techniques",
          "Pêche au coup, feeder, à l'anglaise, avec amorçage"
        ],
        [
          "Appâts",
          "Asticot, ver, graines, maïs, pain"
        ],
        [
          "Postes",
          "Eaux calmes, bordures, fonds nourriciers"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Gobionidae"
        ],
        [
          "Remarque",
          "Espèce cryptique ; hauts bassins Loire/Dordogne/Garonne (Massif central)."
        ]
      ]
    }
  },
  {
    "id": "goujon-ukraine",
    "name": "Goujon d'Ukraine",
    "latin": "Romanogobio belingi",
    "group": "cyprinides",
    "family": "Gobionidae",
    "cdNom": "347994",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Techniques",
          "Pêche au coup, feeder, à l'anglaise, avec amorçage"
        ],
        [
          "Appâts",
          "Asticot, ver, graines, maïs, pain"
        ],
        [
          "Postes",
          "Eaux calmes, bordures, fonds nourriciers"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Gobionidae"
        ],
        [
          "Remarque",
          "Natif NE France (Rhin/Meuse), remonté avec l'amélioration de la qualité de l'eau."
        ]
      ]
    }
  },
  {
    "id": "goujon-occitan",
    "name": "Goujon occitan",
    "latin": "Gobio occitaniae",
    "group": "cyprinides",
    "family": "Gobionidae",
    "cdNom": "388245",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Techniques",
          "Pêche au coup, feeder, à l'anglaise, avec amorçage"
        ],
        [
          "Appâts",
          "Asticot, ver, graines, maïs, pain"
        ],
        [
          "Postes",
          "Eaux calmes, bordures, fonds nourriciers"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Gobionidae"
        ],
        [
          "Remarque",
          "Espèce cryptique ; bassins Adour-Garonne + versant méditerranéen."
        ]
      ]
    }
  },
  {
    "id": "grande-alose",
    "name": "Grande alose",
    "latin": "Alosa alosa",
    "group": "migrateurs",
    "family": "Clupeidae",
    "cdNom": "66967",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "protected": true,
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Espèce protégée / menacée — remise à l'eau"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21 · statut de protection (voir remarque)"
    },
    "fish": {
      "rows": [
        [
          "À savoir",
          "Espèce protégée ou menacée — à ne pas cibler."
        ],
        [
          "Bon geste",
          "Relâchez immédiatement toute capture accidentelle, mains mouillées."
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Clupeidae"
        ],
        [
          "Remarque",
          "Œufs et frayères protégés (arrêté 8 déc. 1988) + Directive Habitats ; pêche sous moratoire sur plusieurs bassins — remise à l'eau, à vérifier localement."
        ]
      ]
    }
  },
  {
    "id": "huchon",
    "name": "Huchon",
    "latin": "Hucho hucho",
    "group": "salmonides",
    "family": "Salmonidae",
    "cdNom": "67794",
    "maille": "70 cm",
    "mailleSub": "national (R436-18)",
    "quota": "—",
    "quotaSub": "—",
    "season": "cat1",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "70 cm (national, R436-18)"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "1ʳᵉ cat. : 2ᵉ samedi de mars → 3ᵉ dimanche de septembre"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Techniques",
          "Pêche à la mouche, au toc, petits leurres (cuiller, vairon)"
        ],
        [
          "Milieu",
          "Eaux vives, fraîches et oxygénées (1ʳᵉ catégorie)"
        ],
        [
          "Éthique",
          "Souvent no-kill / quotas stricts — vérifiez localement"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Salmonidae"
        ],
        [
          "Remarque",
          "Bassin danubien ; présence française marginale, issue d'introductions — à vérifier ; maille 0,70 m."
        ]
      ]
    }
  },
  {
    "id": "ide-melanote",
    "name": "Ide mélanote",
    "latin": "Leuciscus idus",
    "group": "cyprinides",
    "family": "Leuciscidae",
    "cdNom": "67304",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "protected": true,
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Espèce protégée / menacée — remise à l'eau"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21 · statut de protection (voir remarque)"
    },
    "fish": {
      "rows": [
        [
          "À savoir",
          "Espèce protégée ou menacée — à ne pas cibler."
        ],
        [
          "Bon geste",
          "Relâchez immédiatement toute capture accidentelle, mains mouillées."
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Leuciscidae"
        ],
        [
          "Remarque",
          "Protégée (arrêté 8 déc. 1988) ; native NE France (Rhin), aussi introduite (forme orfe dorée)."
        ]
      ]
    }
  },
  {
    "id": "lamproie-de-planer",
    "name": "Lamproie de Planer",
    "latin": "Lampetra planeri",
    "group": "migrateurs",
    "family": "Petromyzontidae",
    "cdNom": "66333",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "cat1",
    "depth": "base",
    "protected": true,
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Espèce protégée / menacée — remise à l'eau"
        ],
        [
          "Période",
          "1ʳᵉ cat. : 2ᵉ samedi de mars → 3ᵉ dimanche de septembre"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21 · statut de protection (voir remarque)"
    },
    "fish": {
      "rows": [
        [
          "À savoir",
          "Espèce protégée ou menacée — à ne pas cibler."
        ],
        [
          "Bon geste",
          "Relâchez immédiatement toute capture accidentelle, mains mouillées."
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Petromyzontidae"
        ],
        [
          "Remarque",
          "Œufs et frayères protégés + Directive Habitats ; petite lamproie résidente non parasite (~15 cm)."
        ]
      ]
    }
  },
  {
    "id": "lamproie-de-riviere",
    "name": "Lamproie de rivière",
    "latin": "Lampetra fluviatilis",
    "group": "migrateurs",
    "family": "Petromyzontidae",
    "cdNom": "66330",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "protected": true,
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Espèce protégée / menacée — remise à l'eau"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21 · statut de protection (voir remarque)"
    },
    "fish": {
      "rows": [
        [
          "À savoir",
          "Espèce protégée ou menacée — à ne pas cibler."
        ],
        [
          "Bon geste",
          "Relâchez immédiatement toute capture accidentelle, mains mouillées."
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Petromyzontidae"
        ],
        [
          "Remarque",
          "Œufs et frayères protégés + Directive Habitats ; migratrice parasite en déclin."
        ]
      ]
    }
  },
  {
    "id": "lamproie-marine",
    "name": "Lamproie marine",
    "latin": "Petromyzon marinus",
    "group": "migrateurs",
    "family": "Petromyzontidae",
    "cdNom": "66315",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "protected": true,
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Espèce protégée / menacée — remise à l'eau"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21 · statut de protection (voir remarque)"
    },
    "fish": {
      "rows": [
        [
          "À savoir",
          "Espèce protégée ou menacée — à ne pas cibler."
        ],
        [
          "Bon geste",
          "Relâchez immédiatement toute capture accidentelle, mains mouillées."
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Petromyzontidae"
        ],
        [
          "Remarque",
          "Œufs et frayères protégés + Directive Habitats ; pêche traditionnelle réglementée par bassin, en déclin."
        ]
      ]
    }
  },
  {
    "id": "loche-d-etang",
    "name": "Loche d'étang",
    "latin": "Misgurnus fossilis",
    "group": "autres",
    "family": "Cobitidae",
    "cdNom": "67534",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "protected": true,
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Espèce protégée / menacée — remise à l'eau"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21 · statut de protection (voir remarque)"
    },
    "fish": {
      "rows": [
        [
          "À savoir",
          "Espèce protégée ou menacée — à ne pas cibler."
        ],
        [
          "Bon geste",
          "Relâchez immédiatement toute capture accidentelle, mains mouillées."
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Cobitidae"
        ],
        [
          "Remarque",
          "Rare et menacée ; œufs et frayères protégés + Directive Habitats — remise à l'eau."
        ]
      ]
    }
  },
  {
    "id": "loche-de-riviere",
    "name": "Loche de rivière",
    "latin": "Cobitis taenia",
    "group": "autres",
    "family": "Cobitidae",
    "cdNom": "67506",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "protected": true,
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Espèce protégée / menacée — remise à l'eau"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21 · statut de protection (voir remarque)"
    },
    "fish": {
      "rows": [
        [
          "À savoir",
          "Espèce protégée ou menacée — à ne pas cibler."
        ],
        [
          "Bon geste",
          "Relâchez immédiatement toute capture accidentelle, mains mouillées."
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Cobitidae"
        ],
        [
          "Remarque",
          "Œufs et frayères protégés + Directive Habitats — remise à l'eau."
        ]
      ]
    }
  },
  {
    "id": "loche-franche",
    "name": "Loche franche",
    "latin": "Barbatula barbatula",
    "group": "autres",
    "family": "Nemacheilidae",
    "cdNom": "67550",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Statut",
          "Petite espèce, rarement ciblée ; parfois utilisée comme vif"
        ],
        [
          "Postes",
          "Fonds et bordures des rivières et ruisseaux"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Nemacheilidae"
        ],
        [
          "Remarque",
          "Non protégée, commune sur fonds de rivières ; à distinguer des loches protégées (Cobitidae)."
        ]
      ]
    }
  },
  {
    "id": "mulet-cabot",
    "name": "Mulet cabot",
    "latin": "Mugil cephalus",
    "group": "migrateurs",
    "family": "Mugilidae",
    "cdNom": "69772",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Techniques",
          "Selon l'espèce ; pêche souvent très réglementée ou fermée"
        ],
        [
          "Rappel",
          "Nombreux migrateurs protégés ou sous quota — vérifiez l'arrêté"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Mugilidae"
        ],
        [
          "Remarque",
          "Mulet amphihalin surtout méditerranéen ; réglementation pêche maritime/estuarienne."
        ]
      ]
    }
  },
  {
    "id": "mulet-dore",
    "name": "Mulet doré",
    "latin": "Chelon auratus",
    "group": "migrateurs",
    "family": "Mugilidae",
    "cdNom": "891947",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Techniques",
          "Selon l'espèce ; pêche souvent très réglementée ou fermée"
        ],
        [
          "Rappel",
          "Nombreux migrateurs protégés ou sous quota — vérifiez l'arrêté"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Mugilidae"
        ],
        [
          "Remarque",
          "Mulet amphihalin ; réglementation pêche maritime/estuarienne."
        ]
      ]
    }
  },
  {
    "id": "mulet-lippu",
    "name": "Mulet lippu",
    "latin": "Chelon labrosus",
    "group": "migrateurs",
    "family": "Mugilidae",
    "cdNom": "69777",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Techniques",
          "Selon l'espèce ; pêche souvent très réglementée ou fermée"
        ],
        [
          "Rappel",
          "Nombreux migrateurs protégés ou sous quota — vérifiez l'arrêté"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Mugilidae"
        ],
        [
          "Remarque",
          "Mulet amphihalin à grosse lèvre ; réglementation pêche maritime/estuarienne."
        ]
      ]
    }
  },
  {
    "id": "mulet-porc",
    "name": "Mulet porc",
    "latin": "Chelon ramada",
    "group": "migrateurs",
    "family": "Mugilidae",
    "cdNom": "891948",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Techniques",
          "Selon l'espèce ; pêche souvent très réglementée ou fermée"
        ],
        [
          "Rappel",
          "Nombreux migrateurs protégés ou sous quota — vérifiez l'arrêté"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Mugilidae"
        ],
        [
          "Remarque",
          "Mulet amphihalin remontant estuaires et basses rivières ; voir réglementation pêche estuarienne."
        ]
      ]
    }
  },
  {
    "id": "omble-chevalier",
    "name": "Omble chevalier",
    "latin": "Salvelinus alpinus",
    "group": "salmonides",
    "family": "Salmonidae",
    "cdNom": "67812",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Techniques",
          "Pêche à la mouche, au toc, petits leurres (cuiller, vairon)"
        ],
        [
          "Milieu",
          "Eaux vives, fraîches et oxygénées (1ʳᵉ catégorie)"
        ],
        [
          "Éthique",
          "Souvent no-kill / quotas stricts — vérifiez localement"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Salmonidae"
        ],
        [
          "Remarque",
          "Natif ; lacs profonds froids (Léman, Bourget, lacs alpins). En plan d'eau (2ᵉ cat.) la fermeture 1ʳᵉ catégorie ne s'applique pas : période ET taille fixées par arrêté préfectoral — à vérifier."
        ]
      ]
    }
  },
  {
    "id": "pseudorasbora",
    "name": "Pseudorasbora (goujon asiatique)",
    "latin": "Pseudorasbora parva",
    "group": "cyprinides",
    "family": "Gobionidae",
    "cdNom": "67415",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Techniques",
          "Pêche au coup, feeder, à l'anglaise, avec amorçage"
        ],
        [
          "Appâts",
          "Asticot, ver, graines, maïs, pain"
        ],
        [
          "Postes",
          "Eaux calmes, bordures, fonds nourriciers"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Gobionidae"
        ],
        [
          "Remarque",
          "Introduit très envahissant ; pas sur R432-5 mais espèce exotique envahissante (règlement UE 1143/2014), vecteur de parasite."
        ]
      ]
    }
  },
  {
    "id": "saumon-atlantique",
    "name": "Saumon atlantique",
    "latin": "Salmo salar",
    "group": "salmonides",
    "family": "Salmonidae",
    "cdNom": "67765",
    "maille": "spéciale",
    "mailleSub": "réglementation spéciale",
    "quota": "—",
    "quotaSub": "—",
    "season": "cat1",
    "depth": "base",
    "protected": true,
    "reg": {
      "rows": [
        [
          "Maille",
          "Réglementation spéciale (voir statut)"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Espèce protégée / menacée — remise à l'eau"
        ],
        [
          "Période",
          "1ʳᵉ cat. : 2ᵉ samedi de mars → 3ᵉ dimanche de septembre"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21 · statut de protection (voir remarque)"
    },
    "fish": {
      "rows": [
        [
          "À savoir",
          "Espèce protégée ou menacée — à ne pas cibler."
        ],
        [
          "Bon geste",
          "Relâchez immédiatement toute capture accidentelle, mains mouillées."
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Salmonidae"
        ],
        [
          "Remarque",
          "Migrateur amphihalin ; réglementation spéciale (TAC, carnet, timbre migrateur), pêche fermée sur de nombreux bassins."
        ]
      ]
    }
  },
  {
    "id": "spirlin",
    "name": "Spirlin",
    "latin": "Alburnoides bipunctatus",
    "group": "cyprinides",
    "family": "Leuciscidae",
    "cdNom": "67104",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Techniques",
          "Pêche au coup, feeder, à l'anglaise, avec amorçage"
        ],
        [
          "Appâts",
          "Asticot, ver, graines, maïs, pain"
        ],
        [
          "Postes",
          "Eaux calmes, bordures, fonds nourriciers"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Leuciscidae"
        ],
        [
          "Remarque",
          "Double rangée de points le long de la ligne latérale ; eaux vives oxygénées."
        ]
      ]
    }
  },
  {
    "id": "toxostome",
    "name": "Toxostome (sofie)",
    "latin": "Parachondrostoma toxostoma",
    "group": "cyprinides",
    "family": "Leuciscidae",
    "cdNom": "458701",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "protected": true,
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Espèce protégée / menacée — remise à l'eau"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21 · statut de protection (voir remarque)"
    },
    "fish": {
      "rows": [
        [
          "À savoir",
          "Espèce protégée ou menacée — à ne pas cibler."
        ],
        [
          "Bon geste",
          "Relâchez immédiatement toute capture accidentelle, mains mouillées."
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Leuciscidae"
        ],
        [
          "Remarque",
          "Directive Habitats An. II ; bouche infère, endémique franco-ibérique menacé. Remise à l'eau conseillée."
        ]
      ]
    }
  },
  {
    "id": "vairon-basque",
    "name": "Vairon basque",
    "latin": "Phoxinus bigerri",
    "group": "autres",
    "family": "Leuciscidae",
    "cdNom": "443292",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Statut",
          "Petite espèce, rarement ciblée ; parfois utilisée comme vif"
        ],
        [
          "Postes",
          "Fonds et bordures des rivières et ruisseaux"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Leuciscidae"
        ],
        [
          "Remarque",
          "Complexe Phoxinus ; bassin de l'Adour et SW."
        ]
      ]
    }
  },
  {
    "id": "vairon",
    "name": "Vairon commun",
    "latin": "Phoxinus phoxinus",
    "group": "autres",
    "family": "Leuciscidae",
    "cdNom": "67404",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Statut",
          "Petite espèce, rarement ciblée ; parfois utilisée comme vif"
        ],
        [
          "Postes",
          "Fonds et bordures des rivières et ruisseaux"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Leuciscidae"
        ],
        [
          "Remarque",
          "Complexe cryptique. Petit poisson de tête de bassin ; appât vif classique."
        ]
      ]
    }
  },
  {
    "id": "vairon-de-garonne",
    "name": "Vairon de Garonne",
    "latin": "Phoxinus dragarum",
    "group": "autres",
    "family": "Leuciscidae",
    "cdNom": "966342",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Statut",
          "Petite espèce, rarement ciblée ; parfois utilisée comme vif"
        ],
        [
          "Postes",
          "Fonds et bordures des rivières et ruisseaux"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Leuciscidae"
        ],
        [
          "Remarque",
          "Décrit en 2020 ; endémique bassin Garonne-Adour."
        ]
      ]
    }
  },
  {
    "id": "vairon-du-danube",
    "name": "Vairon du Danube",
    "latin": "Phoxinus csikii",
    "group": "autres",
    "family": "Leuciscidae",
    "cdNom": "560898",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Statut",
          "Petite espèce, rarement ciblée ; parfois utilisée comme vif"
        ],
        [
          "Postes",
          "Fonds et bordures des rivières et ruisseaux"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Leuciscidae"
        ],
        [
          "Remarque",
          "Complexe Phoxinus ; populations du bassin lémanique / haut Rhin. À vérifier."
        ]
      ]
    }
  },
  {
    "id": "vairon-du-languedoc",
    "name": "Vairon du Languedoc",
    "latin": "Phoxinus septimaniae",
    "group": "autres",
    "family": "Leuciscidae",
    "cdNom": "443293",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Aucun statut national particulier"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21"
    },
    "fish": {
      "rows": [
        [
          "Statut",
          "Petite espèce, rarement ciblée ; parfois utilisée comme vif"
        ],
        [
          "Postes",
          "Fonds et bordures des rivières et ruisseaux"
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Leuciscidae"
        ],
        [
          "Remarque",
          "Espèce cryptique du complexe Phoxinus ; bassin du Rhône / Sud."
        ]
      ]
    }
  },
  {
    "id": "vandoise-rostree",
    "name": "Vandoise rostrée",
    "latin": "Leuciscus burdigalensis",
    "group": "cyprinides",
    "family": "Leuciscidae",
    "cdNom": "67292",
    "maille": "—",
    "mailleSub": "pas de maille nationale",
    "quota": "—",
    "quotaSub": "—",
    "season": "toujours",
    "depth": "base",
    "protected": true,
    "reg": {
      "rows": [
        [
          "Maille",
          "Aucune taille légale nationale"
        ],
        [
          "Quota",
          "Aucun quota national spécifique"
        ],
        [
          "Statut",
          "Espèce protégée / menacée — remise à l'eau"
        ],
        [
          "Période",
          "2ᵉ cat. : ouverte toute l'année"
        ]
      ],
      "note": "Socle national ; un arrêté préfectoral peut être plus strict. Vérifiez localement.",
      "src": "Legifrance R436-18 · R436-21 · statut de protection (voir remarque)"
    },
    "fish": {
      "rows": [
        [
          "À savoir",
          "Espèce protégée ou menacée — à ne pas cibler."
        ],
        [
          "Bon geste",
          "Relâchez immédiatement toute capture accidentelle, mains mouillées."
        ]
      ]
    },
    "bio": {
      "rows": [
        [
          "Famille",
          "Leuciscidae"
        ],
        [
          "Remarque",
          "Décrite par scission de la vandoise ; considérée protégée par extension (à vérifier). Bassins atlantiques SW + Méditerranée."
        ]
      ]
    }
  }
];
