// GENERATED by scripts/enrich-species.mjs - do not edit by hand.
// Official conservation/taxonomy (INPN/MNHN, Licence Ouverte) + morphology (FISHMORPH, CC-BY).
import type { SpeciesEnrichment } from "../types";

export const SPECIES_ENRICHMENT: Record<string, SpeciesEnrichment> = {
  "able-de-heckel": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "67286",
    "morph": {
      "SpecCode": 4782,
      "MBl": 12,
      "BEl": 4.33928169,
      "VEp": 0.433064294,
      "REs": 0.472083149,
      "OGp": 0.47113322,
      "RMl": 0.472242674,
      "BLs": 0.680182624,
      "PFv": 0.12047509,
      "PFs": 0.15772719,
      "CPt": 3.089545793
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "alose-feinte-atlantique": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "66996",
    "morph": {
      "SpecCode": 5355,
      "MBl": 60,
      "BEl": 3.626264914,
      "VEp": 0.584315807,
      "REs": 0.36249818,
      "OGp": 0.546593042,
      "RMl": 0.866203692,
      "BLs": 0.471669221,
      "PFv": 0.192536818,
      "PFs": 0.1380103,
      "CPt": 3.533629851
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "alose-feinte-mediterraneenne": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "66964"
  },
  "amour-blanc": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "67246",
    "morph": {
      "SpecCode": 79,
      "MBl": 150,
      "BEl": 3.96310134,
      "VEp": 0.398785288,
      "REs": 0.255772415,
      "OGp": 0.351890272,
      "RMl": 0.447552663,
      "BLs": 0.48132923,
      "PFv": 0.226864539,
      "PFs": 0.178111854,
      "CPt": 2.281579999
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "apron-du-rhone": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "69378",
    "morph": {
      "SpecCode": 6316,
      "MBl": 22,
      "BEl": 5.920572902,
      "VEp": 0.579225754,
      "REs": 0.400798273,
      "OGp": 0.180751608,
      "RMl": 0.262779224,
      "BLs": 0.635329713,
      "PFv": 0.54764211,
      "PFs": 0.185086397,
      "CPt": 3.12319119
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "aspe": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "200255",
    "morph": {
      "SpecCode": 4783,
      "MBl": 120,
      "BEl": 3.995498524,
      "VEp": 0.591368334,
      "REs": 0.226139983,
      "OGp": 0.562939922,
      "RMl": 0.659581401,
      "BLs": 0.427810753,
      "PFv": 0.346982617,
      "PFs": 0.174020601,
      "CPt": 2.212635366
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "barbeau-meridional": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "67179",
    "morph": {
      "SpecCode": 5424,
      "MBl": 27,
      "BEl": 4.429396308,
      "VEp": 0.627147112,
      "REs": 0.369288025,
      "OGp": 0.389645339,
      "RMl": 0.424999824,
      "BLs": 0.529538889,
      "PFv": 0.303137527,
      "PFs": 0.195501026,
      "CPt": 2.20932337
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "black-bass-petite-bouche": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "69344",
    "morph": {
      "SpecCode": 3382,
      "MBl": 69,
      "BEl": 3.341377865,
      "VEp": 0.652592702,
      "REs": 0.332552432,
      "OGp": 0.601273409,
      "RMl": 0.656669649,
      "BLs": 0.610300565,
      "PFv": 0.389737954,
      "PFs": 0.171659093,
      "CPt": 2.828317774
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "blageon": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "67335",
    "morph": {
      "SpecCode": 6462,
      "MBl": 25,
      "BEl": 4.824742268,
      "VEp": 0.580587629,
      "REs": 0.4,
      "OGp": 0.49956701,
      "RMl": 0.476683333,
      "BLs": 0.618556701,
      "PFv": 0.216412371,
      "PFs": 0.158638889,
      "CPt": 2.966597256
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "blennie-fluviatile": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "1005993"
  },
  "bouviere": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "67420",
    "morph": {
      "SpecCode": 4483,
      "MBl": 11.2,
      "BEl": 2.460751434,
      "VEp": 0.460064888,
      "REs": 0.509007617,
      "OGp": 0.384101293,
      "RMl": 0.378283554,
      "BLs": 0.3342143,
      "PFv": 0.250959949,
      "PFs": 0.135593304,
      "CPt": 2.319255319
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "breme-bordeliere": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "67203",
    "morph": {
      "SpecCode": 4471,
      "MBl": 45.5,
      "BEl": 2.485815404,
      "VEp": 0.459238245,
      "REs": 0.503950374,
      "OGp": 0.36573788,
      "RMl": 0.331276177,
      "BLs": 0.354092467,
      "PFv": 0.308156845,
      "PFs": 0.17880226,
      "CPt": 2.999490653
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "brochet-aquitain": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "781090"
  },
  "carassin-argente": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "67210",
    "morph": {
      "SpecCode": 6376,
      "MBl": 46.6,
      "BEl": 2.231072982,
      "VEp": 0.498755109,
      "REs": 0.374346839,
      "OGp": 0.442976697,
      "RMl": 0.365432552,
      "BLs": 0.401313767,
      "PFv": 0.241731916,
      "PFs": 0.187138726,
      "CPt": 1.893603243
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "poisson-rouge": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "67208",
    "morph": {
      "SpecCode": 271,
      "MBl": 59,
      "BEl": 2.63423759,
      "VEp": 0.438711954,
      "REs": 0.32616582,
      "OGp": 0.401780205,
      "RMl": 0.35966378,
      "BLs": 0.409389939,
      "PFv": 0.210317985,
      "PFs": 0.180506568,
      "CPt": 2.282849533
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "carpe-argentee": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "67275",
    "morph": {
      "SpecCode": 274,
      "MBl": 105,
      "BEl": 3.385020677,
      "VEp": 0.493936371,
      "REs": 0.316898111,
      "OGp": 0.578815594,
      "RMl": 0.368427817,
      "BLs": 0.456579498,
      "PFv": 0.297775269,
      "PFs": 0.19777752,
      "CPt": 2.873008629
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "chabot-commun": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "69182",
    "morph": {
      "SpecCode": 2439,
      "MBl": 18,
      "BEl": 5.987026227,
      "VEp": 0.702836958,
      "REs": 0.402236592,
      "OGp": 0.5019123,
      "RMl": 0.490233659,
      "BLs": 0.779231573,
      "PFv": 0.497334468,
      "PFs": 0.229832325,
      "CPt": 2.699277598
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "chabot-fluviatile": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "416658"
  },
  "chevesne-catalan": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "459646"
  },
  "coregone-lavaret": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "67862",
    "morph": {
      "SpecCode": 232,
      "MBl": 73,
      "BEl": 4.227334121,
      "VEp": 0.535312147,
      "REs": 0.433651344,
      "OGp": 0.480285458,
      "RMl": 0.481805498,
      "BLs": 0.34440707,
      "PFv": 0.288432317,
      "PFs": 0.126790896,
      "CPt": 3.023632403
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "cristivomer": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "67819",
    "morph": {
      "SpecCode": 248,
      "MBl": 150,
      "BEl": 4.850792773,
      "VEp": 0.642957227,
      "REs": 0.329173077,
      "OGp": 0.478585914,
      "RMl": 1.014865385,
      "BLs": 0.479351032,
      "PFv": 0.242920354,
      "PFs": 0.16313325,
      "CPt": 3.656679023
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "epinoche": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "69010",
    "morph": {
      "SpecCode": 2420,
      "MBl": 11,
      "BEl": 4.045420061,
      "VEp": 0.571305628,
      "REs": 0.603812088,
      "OGp": 0.501718631,
      "RMl": 0.409239693,
      "BLs": 0.565954685,
      "PFv": 0.489701434,
      "PFs": 0.158644254,
      "CPt": 4.080636108
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "epinochette": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "200259"
  },
  "esturgeon-europeen": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "66775",
    "morph": {
      "SpecCode": 2066,
      "MBl": 600,
      "BEl": 8.307055489,
      "VEp": 0.343421838,
      "REs": 0.311984323,
      "OGp": 0,
      "RMl": 0.196335259,
      "BLs": 0.433890215,
      "PFv": 0,
      "CPt": 3.30320441
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "flet": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "70554",
    "morph": {
      "SpecCode": 1341,
      "MBl": 60,
      "BEl": 2.239534821,
      "VEp": 0.610478062,
      "REs": 0.320122103,
      "OGp": 0.51860754,
      "RMl": 0.395850984,
      "BLs": 0.30865788,
      "PFv": 0.464029012,
      "PFs": 0.137147459,
      "CPt": 2.357198818
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "gambusie": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "68827",
    "morph": {
      "SpecCode": 4521,
      "MBl": 8,
      "BEl": 3.538037438,
      "VEp": 0.474599696,
      "REs": 0.583510123,
      "OGp": 0.573699656,
      "RMl": 0.284539713,
      "BLs": 0.484924869,
      "PFv": 0.432610341,
      "PFs": 0.18754181,
      "CPt": 2.135950413
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "goujon-auvergne": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "388244"
  },
  "goujon-ukraine": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "347994"
  },
  "goujon-occitan": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "388245"
  },
  "grande-alose": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "66967",
    "morph": {
      "SpecCode": 101,
      "MBl": 83,
      "BEl": 3.910500536,
      "VEp": 0.531244891,
      "REs": 0.386758926,
      "OGp": 0.425779382,
      "RMl": 0.779108774,
      "BLs": 0.546883987,
      "PFv": 0.144566277,
      "PFs": 0.158360041,
      "CPt": 3.053753725
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "huchon": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "67794",
    "morph": {
      "SpecCode": 4664,
      "MBl": 150,
      "BEl": 5.480817184,
      "VEp": 0.575952812,
      "REs": 0.201,
      "OGp": 0.504487171,
      "RMl": 0.85055102,
      "BLs": 0.620229612,
      "PFv": 0.196460894,
      "PFs": 0.136473126,
      "CPt": 3.168346735
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "ide-melanote": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "67304",
    "morph": {
      "SpecCode": 2801,
      "MBl": 85,
      "BEl": 3.583934434,
      "VEp": 0.520366586,
      "REs": 0.406840754,
      "OGp": 0.542585138,
      "RMl": 0.460805228,
      "BLs": 0.465069806,
      "PFv": 0.240230979,
      "PFs": 0.185600454,
      "CPt": 2.150565321
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "lamproie-de-planer": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "66333"
  },
  "lamproie-de-riviere": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "66330"
  },
  "lamproie-marine": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "66315"
  },
  "loche-d-etang": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "67534",
    "morph": {
      "SpecCode": 4790,
      "MBl": 30,
      "BEl": 7.466360508,
      "VEp": 0.454787158,
      "REs": 0.191796586,
      "OGp": 0.164344414,
      "BLs": 0.518909773,
      "PFv": 0.13868115,
      "CPt": 2.006729063
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "loche-de-riviere": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "67506",
    "morph": {
      "SpecCode": 6378,
      "MBl": 14,
      "BEl": 6.750121118,
      "VEp": 0.618919452,
      "REs": 0.286353167,
      "OGp": 0,
      "BLs": 0.802443882,
      "PFv": 0.161490015,
      "PFs": 0.114149461,
      "CPt": 1.9990005
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "loche-franche": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "67550",
    "morph": {
      "SpecCode": 6377,
      "MBl": 21,
      "BEl": 6.724161164,
      "VEp": 0.489219782,
      "REs": 0.30066,
      "OGp": 0,
      "BLs": 0.673763644,
      "PFv": 0,
      "PFs": 0.144789579,
      "CPt": 1.754811321
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "mulet-cabot": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "69772",
    "morph": {
      "SpecCode": 785,
      "MBl": 100,
      "BEl": 4.00102005,
      "VEp": 0.555333459,
      "REs": 0.498534249,
      "OGp": 0.589632462,
      "RMl": 0.292992905,
      "BLs": 0.521260137,
      "PFv": 0.674227773,
      "PFs": 0.195523875,
      "CPt": 2.442879162
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "mulet-dore": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "891947",
    "morph": {
      "SpecCode": 1735,
      "MBl": 59,
      "BEl": 4.137897164,
      "VEp": 0.661537221,
      "REs": 0.477387413,
      "OGp": 0.646485784,
      "RMl": 0.278860802,
      "BLs": 0.398701742,
      "PFv": 0.719973048,
      "PFs": 0.197242778,
      "CPt": 3.557240412
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "mulet-lippu": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "69777",
    "morph": {
      "SpecCode": 2499,
      "MBl": 75,
      "BEl": 3.918653099,
      "VEp": 0.534372112,
      "REs": 0.421724147,
      "OGp": 0.495619266,
      "RMl": 0.21572883,
      "BLs": 0.392515837,
      "PFv": 0.617923579,
      "PFs": 0.168065876,
      "CPt": 3.044644887
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "mulet-porc": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "891948",
    "morph": {
      "SpecCode": 4583,
      "MBl": 70,
      "BEl": 4.34066076,
      "VEp": 0.52997701,
      "REs": 0.333333333,
      "OGp": 0.623279002,
      "RMl": 0.360490196,
      "BLs": 0.439128975,
      "PFv": 0.573287182,
      "PFs": 0.140881139,
      "CPt": 2.681247434
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "omble-chevalier": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "67812",
    "morph": {
      "SpecCode": 247,
      "MBl": 107,
      "BEl": 4.256032317,
      "VEp": 0.640026718,
      "REs": 0.271921287,
      "OGp": 0.54224371,
      "RMl": 0.747663551,
      "BLs": 0.477158943,
      "PFv": 0.324259677,
      "PFs": 0.168286183,
      "CPt": 2.865442308
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "pseudorasbora": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "67415",
    "morph": {
      "SpecCode": 4691,
      "MBl": 12.5,
      "BEl": 4.215011163,
      "VEp": 0.496265565,
      "REs": 0.4223579,
      "OGp": 0.510742615,
      "RMl": 0.277717671,
      "BLs": 0.515789975,
      "PFv": 0.255900356,
      "PFs": 0.150239916,
      "CPt": 2.273507293
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "saumon-atlantique": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "67765",
    "morph": {
      "SpecCode": 236,
      "MBl": 150,
      "BEl": 3.956530893,
      "VEp": 0.467510023,
      "REs": 0.20859375,
      "OGp": 0.424334804,
      "RMl": 0.81703125,
      "BLs": 0.421093263,
      "PFv": 0.244620095,
      "PFs": 0.124212585,
      "CPt": 3.076443168
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "spirlin": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "67104",
    "morph": {
      "SpecCode": 4875,
      "MBl": 18.5,
      "BEl": 3.512796769,
      "VEp": 0.525739563,
      "REs": 0.623262053,
      "OGp": 0.488984023,
      "RMl": 0.580383492,
      "BLs": 0.451359456,
      "PFv": 0.268386674,
      "PFs": 0.204675647,
      "CPt": 3.342143807
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "toxostome": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "458701",
    "morph": {
      "SpecCode": 4477,
      "MBl": 30,
      "BEl": 4.39650385,
      "VEp": 0.547940595,
      "REs": 0.432179532,
      "OGp": 0.465760725,
      "RMl": 0.293643431,
      "BLs": 0.438372109,
      "PFv": 0.236337246,
      "PFs": 0.156697815,
      "CPt": 2.624828153
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "vairon-basque": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "443292"
  },
  "vairon": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "67404",
    "morph": {
      "SpecCode": 4661,
      "MBl": 14,
      "BEl": 4.854359173,
      "VEp": 0.453321275,
      "REs": 0.46132951,
      "OGp": 0.257509475,
      "RMl": 0.386550293,
      "BLs": 0.530481051,
      "PFv": 0.262041559,
      "PFs": 0.151901614,
      "CPt": 2.332147296
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "vairon-de-garonne": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "966342"
  },
  "vairon-du-danube": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "560898"
  },
  "vairon-du-languedoc": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "443293"
  },
  "vandoise-rostree": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "cdNom": "67292",
    "morph": {
      "SpecCode": 53236,
      "MBl": 40,
      "BEl": 4.088354127,
      "VEp": 0.497896326,
      "REs": 0.408502122,
      "OGp": 0.319111824,
      "RMl": 0.369156594,
      "BLs": 0.485192651,
      "PFv": 0.250707591,
      "PFs": 0.166581396,
      "CPt": 2.993740354
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "sandre": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "morph": {
      "SpecCode": 360,
      "MBl": 100,
      "BEl": 4.436274074,
      "VEp": 0.388211694,
      "REs": 0.493332767,
      "OGp": 0.228995964,
      "RMl": 0.653749788,
      "BLs": 0.380940055,
      "PFv": 0.34755846,
      "PFs": 0.146019498,
      "CPt": 3.388258784
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "brochet": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "morph": {
      "SpecCode": 258,
      "MBl": 150,
      "BEl": 6.005228693,
      "VEp": 0.621035943,
      "REs": 0.264733496,
      "OGp": 0.459201629,
      "RMl": 1.280487591,
      "BLs": 0.625750807,
      "PFv": 0.165010858,
      "PFs": 0.106231483,
      "CPt": 2.459066917
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "silure": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "morph": {
      "SpecCode": 289,
      "MBl": 500,
      "BEl": 5.83994642,
      "VEp": 0.57179471,
      "REs": 0.210233364,
      "OGp": 0.526157027,
      "RMl": 0.379009648,
      "BLs": 0.511623001,
      "PFv": 0.423543433,
      "PFs": 0.106003825,
      "CPt": 2.200067986
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "perche-soleil": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "morph": {
      "SpecCode": 3372,
      "MBl": 40,
      "BEl": 2.148928303,
      "VEp": 0.523731719,
      "REs": 0.330129489,
      "OGp": 0.464434835,
      "RMl": 0.301593427,
      "BLs": 0.494616905,
      "PFv": 0.318648272,
      "PFs": 0.250377931,
      "CPt": 2.415496154
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "perche": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "morph": {
      "SpecCode": 358,
      "MBl": 60,
      "BEl": 3.284140914,
      "VEp": 0.5129916,
      "REs": 0.360131605,
      "OGp": 0.436473059,
      "RMl": 0.650261995,
      "BLs": 0.508425097,
      "PFv": 0.361675652,
      "PFs": 0.183462986,
      "CPt": 3.009296765
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "truite-fario": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "morph": {
      "SpecCode": 238,
      "MBl": 140,
      "BEl": 4.174222302,
      "VEp": 0.605609036,
      "REs": 0.304057662,
      "OGp": 0.520692859,
      "RMl": 0.874308435,
      "BLs": 0.463962026,
      "PFv": 0.25498346,
      "PFs": 0.141035041,
      "CPt": 2.274147539
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "carpe": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "morph": {
      "SpecCode": 1450,
      "MBl": 120,
      "BEl": 3.481135273,
      "VEp": 0.510936185,
      "REs": 0.182045455,
      "OGp": 0.307949315,
      "RMl": 0.346172727,
      "BLs": 0.48104781,
      "PFv": 0.258020926,
      "PFs": 0.178656382,
      "CPt": 2.637145238
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "gardon": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "morph": {
      "SpecCode": 272,
      "MBl": 50.2,
      "BEl": 3.218972304,
      "VEp": 0.455062235,
      "REs": 0.431532266,
      "OGp": 0.379343846,
      "RMl": 0.344102056,
      "BLs": 0.417817861,
      "PFv": 0.250272659,
      "PFs": 0.161840208,
      "CPt": 3.213864568
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "barbeau": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "morph": {
      "SpecCode": 4472,
      "MBl": 120,
      "BEl": 4.068372397,
      "VEp": 0.371264757,
      "REs": 0.23787234,
      "OGp": 0,
      "RMl": 0.298638298,
      "BLs": 0.388291764,
      "PFv": 0.239724726,
      "PFs": 0.155661105,
      "CPt": 2.304620804
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "poisson-chat": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "morph": {
      "SpecCode": 291,
      "MBl": 66,
      "BEl": 4.10148913,
      "VEp": 0.48507337,
      "REs": 0.210539107,
      "OGp": 0.404241848,
      "RMl": 0.326590325,
      "BLs": 0.570236413,
      "PFv": 0.389497283,
      "PFs": 0.157155275,
      "CPt": 2.213600411
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "black-bass": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "morph": {
      "SpecCode": 3385,
      "MBl": 97,
      "BEl": 2.897989032,
      "VEp": 0.598507859,
      "REs": 0.271130617,
      "OGp": 0.546138912,
      "RMl": 0.84366518,
      "BLs": 0.471328002,
      "PFv": 0.326692452,
      "PFs": 0.172997466,
      "CPt": 2.367404334
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "breme": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "morph": {
      "SpecCode": 268,
      "MBl": 82,
      "BEl": 2.546312456,
      "VEp": 0.546875558,
      "REs": 0.341575092,
      "OGp": 0.512381063,
      "RMl": 0.26297763,
      "BLs": 0.398473812,
      "PFv": 0.36893787,
      "PFs": 0.194460833,
      "CPt": 3.01447933
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "tanche": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "morph": {
      "SpecCode": 269,
      "MBl": 70,
      "BEl": 2.824172996,
      "VEp": 0.519115068,
      "REs": 0.209968823,
      "OGp": 0.434014665,
      "RMl": 0.355218766,
      "BLs": 0.46285427,
      "PFv": 0.247651987,
      "PFs": 0.193467696,
      "CPt": 1.720606732
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "ablette": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "morph": {
      "SpecCode": 4730,
      "MBl": 25,
      "BEl": 4.253526855,
      "VEp": 0.559971056,
      "REs": 0.540985824,
      "OGp": 0.559971056,
      "RMl": 0.441100168,
      "BLs": 0.429576461,
      "PFv": 0.2766026,
      "PFs": 0.152191702,
      "CPt": 1.942321838
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "chevesne": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "morph": {
      "SpecCode": 4482,
      "MBl": 85,
      "BEl": 3.572677392,
      "VEp": 0.608186863,
      "REs": 0.359761796,
      "OGp": 0.532037571,
      "RMl": 0.46206342,
      "BLs": 0.356574909,
      "PFv": 0.344020273,
      "PFs": 0.172295685,
      "CPt": 2.6003
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "hotu": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "morph": {
      "SpecCode": 4878,
      "MBl": 50,
      "BEl": 3.959408526,
      "VEp": 0.468442813,
      "REs": 0.363636364,
      "OGp": 0.321312998,
      "RMl": 0.313872727,
      "BLs": 0.418782789,
      "PFv": 0.276320498,
      "PFs": 0.15578047,
      "CPt": 2.31372549
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "goujon": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "morph": {
      "SpecCode": 4478,
      "MBl": 21,
      "BEl": 4.762858911,
      "VEp": 0.577226902,
      "REs": 0.441565619,
      "OGp": 0.173043232,
      "RMl": 0.298397321,
      "BLs": 0.645405621,
      "PFv": 0.149628107,
      "PFs": 0.188987027,
      "CPt": 1.980330344
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "rotengle": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "morph": {
      "SpecCode": 2951,
      "MBl": 51,
      "BEl": 3.005719096,
      "VEp": 0.517721457,
      "REs": 0.443946643,
      "OGp": 0.511645125,
      "RMl": 0.342106838,
      "BLs": 0.442462444,
      "PFv": 0.292714738,
      "PFs": 0.179402632,
      "CPt": 3.098780467
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "ombre": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "morph": {
      "SpecCode": 4605,
      "MBl": 60,
      "BEl": 4.758397322,
      "VEp": 0.62623673,
      "REs": 0.432042983,
      "OGp": 0.469727328,
      "RMl": 0.5407018,
      "BLs": 0.429672819,
      "PFv": 0.314898013,
      "PFs": 0.161065146,
      "CPt": 3.632745098
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "omble-fontaine": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "morph": {
      "SpecCode": 246,
      "MBl": 86,
      "BEl": 3.471882099,
      "VEp": 0.6354576,
      "REs": 0.320154569,
      "OGp": 0.56764812,
      "RMl": 0.937220636,
      "BLs": 0.438863261,
      "PFv": 0.277230417,
      "PFs": 0.153272033,
      "CPt": 2.280604817
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "truite-arc-en-ciel": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "morph": {
      "SpecCode": 239,
      "MBl": 122,
      "BEl": 3.945403278,
      "VEp": 0.603331072,
      "REs": 0.318734538,
      "OGp": 0.50286397,
      "RMl": 0.825899299,
      "BLs": 0.525988454,
      "PFv": 0.243535353,
      "PFs": 0.155970227,
      "CPt": 2.650049006
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "anguille": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "morph": {
      "SpecCode": 35,
      "MBl": 133,
      "BEl": 16.2191429,
      "VEp": 0.821233167,
      "REs": 0.249665422,
      "OGp": 0.720516313,
      "RMl": 0.394942594,
      "BLs": 0.634091873,
      "PFv": 0.604546774,
      "PFs": 0.04466753,
      "CPt": 0
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "carassin": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "morph": {
      "SpecCode": 270,
      "MBl": 64,
      "BEl": 2.139643611,
      "VEp": 0.524307878,
      "REs": 0.292355157,
      "OGp": 0.475862214,
      "RMl": 0.27207058,
      "BLs": 0.384168607,
      "PFv": 0.270874978,
      "PFs": 0.182361334,
      "CPt": 1.701818629
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  },
  "vandoise": {
    "source": "INPN/MNHN TaxRef v18 & BDC-Statuts (Licence Ouverte)",
    "morph": {
      "SpecCode": 4662,
      "MBl": 40,
      "BEl": 4.559024887,
      "VEp": 0.476097198,
      "REs": 0.443884164,
      "OGp": 0.324335707,
      "RMl": 0.359510662,
      "BLs": 0.551620454,
      "PFv": 0.226099646,
      "PFs": 0.163173148,
      "CPt": 2.808990347
    },
    "morphSource": "FISHMORPH (Brosse et al. 2021, CC-BY)"
  }
};
